### ISSUE TITLE
missing objects in new bimserver

### ISSUE THREAD

**Issue by halmsx** [opensourceBIM/BIMserver#1005]
seems like some of objects from my models are missing in both version 1.5.147 and 1.5.150. model is perfect in 1.5.125.

Operating system : Mac OS 10.14 and Linux Ubuntu 18.10
Bimserver jar/war version : 1.5.147-150
Browser : Safari, Chrome

in these screenshots, some walls can be seen not there

<img width="924" alt="Screen Shot 2019-07-14 at 11 35 58 AM" src="https://user-images.githubusercontent.com/7524731/61179091-01c67300-a62e-11e9-8d38-320542ae3894.png">

<img width="913" alt="Screen Shot 2019-07-14 at 11 42 40 AM" src="https://user-images.githubusercontent.com/7524731/61179101-44884b00-a62e-11e9-9a1f-7b59dfb07c98.png">

**Comment by hlg** [comment]
Is this issue still relevant? If so, could you try to see whether it still appears in latest BIMserver and BIMsurfer versions? In that case could you perhaps share some debug files if any or (parts of) the original file?

**Comment by hlg** [comment]
A couple of similar issues have been solved with a later version of the IfcOpenShell plugin (e.g. #1112, #1106, #1100). Likely this issue is also resolved the same way, but without sample data is not possible to verify. Thus I am closing this issue. If you find this data still causes the issue, please post the data and reopen the issue.
