### ISSUE TITLE
Why Bim Server Not free RAM after Model upload ?

### ISSUE THREAD

**Issue by raviarsuda05** [opensourceBIM/BIMserver#1018]
I upload model. after uploading model will getting checking status. but Bim will not free Server RAM. 

I use apache Tomcat 4.5.43 with Bimserver-1.5.147.war

**Comment by rubendel** [comment]
That's an extremely old version of Tomcat. How did you determine how much memory was being used by BIMserver?

**Comment by raviarsuda05** [comment]
16 CP and 64 GB RAM

**Comment by raviarsuda05** [comment]
yes Its old version but i also replace apache tomcat 4.5.43 to apache tomcat 8.5.43. till getting same issue.

**Comment by rubendel** [comment]
Please try to be correct. 16 CPUs sounds unbelievable, maybe you mean CPU cores? What I asked was how you determined how much memory BIMserver **uses**, not how much memory is in the machine.

**Comment by raviarsuda05** [comment]
Bim server use 4 to 6 GB RAM. But When i am uploading model RAM going high. but after done to upload model BIM not release machine RAM.

**Comment by rubendel** [comment]
BIMserver is written in Java. Java runs on a JVM. The JVM does not give back memory to the OS once it has acquired memory. It doesn't do that because acquiring memory from the OS is costly.

That's why I asked how you measured this memory usage. What is important is the amount of memory BIMserver actually uses, not how much the JVM uses (which is what you see in your OS it's process overview).

Also, BerkeleyDB can use up to 50% of the allocated JVM heap memory for caching purposes, which makes accessing the database faster.

**Comment by raviarsuda05** [comment]
![image](https://user-images.githubusercontent.com/52482893/62195942-b1c00e00-b39a-11e9-8562-09dd41048cf3.png)

you can see server log.

**Comment by rubendel** [comment]
Server log would be useful yes.

**Comment by raviarsuda05** [comment]
so now you can see that bimserver taken lot of RAM here not doing any action on BImserver now.
