### ISSUE TITLE
[LowLevelInterface] - [SetAttribute] - Can't set a boolean attribute

### ISSUE THREAD

**Issue by aurelien-gille** [opensourceBIM/BIMserver#1064]
Hello, 

I've some troubles trying to use the` LowLevelInterface.setBooleanAttribute(Long tid, Long oid, String attributeName, Boolean value)`
When the commit comes it stop on 
```
org.bimserver.changes.SetAttributeChange.execute(SetAttributeChange.java:123)
object.set(eAttribute.getName(), eEnum.getEEnumLiteral(((String) value).toUpperCase()).getInstance());
```
As value is a boolean (tried with Boolean too) and can't be cast into a String

I tried to swith to `LowLevelInterface.setStringAttribute(Long tid, Long oid, String attributeName, String value)` with "TRUE" or "FALSE" as value but it stop on 
```
org.bimserver.shared.HashMapVirtualObject.writePrimitiveValue (HashMapVirtualObject.java:445)
"buffer.put(((Boolean) value) ? (byte) 1 : (byte) 0);"

```
The targeted object is a IfcCompositeCurveSegment and its attribute is SameSense

Can you please enlighten me if I did something wrong ?

**Comment by rubendel** [comment]
The `IfcCompositeCurveSegment.SameSense` field in BIMserver is of type `Tristate`. This seems to be an error because the `Tristate` enum is only required for optional boolean fields in the IFC schema, which this is not. Anyways, changing it (and probably other field in other classes as well) would be too much work/impact right now, so I checked-in a fix that will detect the Tristate explicitly, and accept a boolean true/false. In this case it should never be null. So your use case should work after this update, which will be in the 1.5.179 build.

**Comment by aurelien-gille** [comment]
Oh ! 
Thanks a lot ! I'll wait for it

**Comment by rubendel** [comment]
So this should be working in the 1.5.180 release of November 29, please reopen if it's not.
