### ISSUE TITLE
Query stdlib inverse relationships

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#1081]
I am using a query like this to retrieve a range of selected entities of type `IfcProduct` together with the spatial structures they are contained in. Some of the selected entities share the same containing structure.

```
{
  "types": [
    { "name": "IfcSlab", "includeAllSubTypes": true },
    { "name": "IfcWall", "includeAllSubTypes": true }
  ],
  "includes": [
    "ifc4-stdlib:ContainedInStructure"
  ]
}
```

Some of the selected entities share the same containing structure, but nonetheless for the containment (and similar for the decomposition) relationships, the result only contains one-to-one relations, for example:

```
#1= IFCSLAB('0GY1GrnlqcJxGvQRJnc2pS',$,'Slab1',$,$,$,$,$,.FLOOR.);
#2= IFCSLAB('1qD6E40JdLGOUfoPEB28UG',$,'Slab2',$,$,$,$,$,.FLOOR.);
#3= IFCWALLSTANDARDCASE('36jX$zrDQFJg5KoMWSrrxc',$,'Wall1',$,$,$,$,$');
#4= IFCBUILDINGSTOREY('2WSdUCQgLA19aleUi6sdSw',$,'Ground Floor',$,$,$,$,$,.ELEMENT.,0.);
#5= IFCRELCONTAINEDINSPATIALSTRUCTURE('07UAzyn2XWBrjM467ocCR6',$,$,$,(#1),#4);
```

In the original IFC, the relation has a higher cardinality and I would expect the same as a result:

```
#5= IFCRELCONTAINEDINSPATIALSTRUCTURE('07UAzyn2XWBrjM467ocCR6',$,$,$,(#1,#2,#3),#4);
```

I assume this is similar for any one-to-many relationship which is queried through its inverse from the many side.

Is this intended behaviour and has always been like this or is it a regression? Or did I miss something in the query?

**Comment by rubendel** [comment]
Sorry for the late reply. Just tested this on an ifc2x3tc1 model and I got the expected result (multiple items in the `IFCRELCONTAINEDINSPATIALSTRUCTURE` list). Can you share the IFC4 model this happens in? Could well be that something is missing in the ifc4stdlib.

**Comment by hlg** [comment]
I used the FZK house [1] and also tried also tried the IFC2x3 version [2].

I do get three elements for the upper storey, but there should be more than this - it's just slabs included, no walls. There is only a single slab referred from `IFCRELCONTAINEDINSPATIALSTRUCTURE` in the ground floor. If I swap the order of walls and slabs in the query, I get the same result in IFC4 and one wall plus the slabs in IFC2x3. 

[1] http://www.ifcwiki.org/images/e/e3/AC20-FZK-Haus.ifc
[2] https://raw.githubusercontent.com/opensourceBIM/TestFiles/master/TestData/data/AC11-FZK-Haus-IFC.ifc

**Comment by rubendel** [comment]
Ah yes, what you can do is add `doublebuffer: true` to the beginning of the query, I think that will give the expected results.

I'll try and explain how the json filter language is processed in BIMserver, if it makes sense, I'll move it to a wiki page.

One of the goals for the filter language was to be able to execute the queries in a streaming fashion, so not loading all the query results into memory at once, but one at a time, and also sending the data to the selected serializer while the query is still executing. One downside of this is that as soon as an entity is sent to the serializer (and they do get send as soon as they are encountered in the query path), it cannot be altered. Since BIMserver does not known in advance which objects are going to be serialized, it can only write down the references of the objects it has already sent (it keeps track of those), and in some cases other ones it does know it's going to be sending (for example top-level `oids` queries).

Most (simple) queries seem to work fine this way, but as soon as the same objects are encountered in different query paths, or when different query paths encounter objects that reference each other, but where the references are not followed, things can go wrong. So basically what the `doublebuffer` argument does is:
- Execute the query a first time, not sending the results to the serializer, and only keeping track of the Object IDs of the objects that are resolved
- Execute the query a second time, this time it already known which IDs are going to be sent, so everything should be stitched together nicely.

The downsides of this approach (which maybe should be the default, given the unexpectedness) are:
- Startup-time (before the first entity is sent over the line) will be higher
- Overall query time will also be higher (but not a lot, since the second time changes are all the data is already cached)
- Memory consumption should be equal, since a list of OIDs is kept anyways.

Hope this makes sense, and your input on whether `doublebuffer: true` should be the default is appreciated.

**Comment by hlg** [comment]
Yes, with the `doublebuffer` flag the query results come out right. Your explanation makes sense and should be included in the Wiki.

I also tried to flip the query, but then, without `doublebuffer` I get too many `relatedElements` references. Worse, the referenced elements are not actually in the result, such that the IFC becomes invalid. It is clear now, why this happens - because the references are written before the type restriction is made.

```
{
  "type": "IfcRelContainedInSpatialStructure",
  "include": {
    "type": "IfcRelContainedInSpatialStructure",
    "fields": ["RelatedElements", "RelatingStructure"],
    "outputTypes": ["IfcSlab", "IfcWall", "IfcWallStandardCase", "IfcBuildingStorey", "IfcBuilding" ]
  }
}
```

Btw. it would be nice if one could  specify supertypes for `outputTypes` as well, same as for `types`.

Whether to make `doublebuffer: true` the default setting? At least for the streaming serializers I guess so, given that some queries may not be possible to specify such that they yield correct results otherwise. Then you can switch the doublebuffer off to optimize for speed if you are sure about the query. For my taste it is easier to grasp that an additional setting optimizes for speed and may sacrifice correctness, rather than guarantee correctness and sacrifice speed.

It seems as if the non-streaming wouldn't need a second run. But you wanted to remove them anyway, IIRC?

If found a way to write the original query without the need for doublebuffers, but of course, for more complex element restrictions this would not work either.

```
{
  "types": ["IfcSlab", "IfcWall", "IfcWallStandardCase"],
  "includes": ["ifc4-stdlib:ContainedInStructure" ]
}
```

**Comment by rubendel** [comment]
Ok thanks, I just made double buffering the default. Also the bug mentioned in https://github.com/opensourceBIM/BIMserver/issues/1098 is fixed. The non streaming serializers do indeed not need the double buffering, it's actually only applied to queries that are processed by streaming serializers.

I have deprecated the json non-streaming serializers as of today, as they are constantly lagging behind in features/updates, and I don't see any use for them anymore.

Just added the ability to use "complex" type definitions for outputTypes. You can now for example do:
```json
{
  "type": "IfcRelContainedInSpatialStructure",
  "include": {
    "type": "IfcRelContainedInSpatialStructure",
    "fields": ["RelatedElements", "RelatingStructure"],
    "outputTypes": [{
      "name": "IfcProduct", 
      "includeAllSubTypes": true
    }]
  }
}
```

**Comment by hlg** [comment]
Great, thanks!
