### ISSUE TITLE
BimServer error when upload ifc

### ISSUE THREAD

**Issue by JanoSlivka** [opensourceBIM/BIMserver#1084]
Hello

I upload ifc from [http://openifcmodel.cs.auckland.ac.nz/Model/Details/304](url). I show error message: Cannot store a IfcBuildingElementProxy in IfcRelConnectsPortToElement.RelatedElement of type IfcDistributionElement.

Thanks for help

**Comment by hlg** [comment]
The IFC data is invalid. Check the following lines from the file.

    #2221325= IFCRELCONNECTSPORTTOELEMENT('07KWWRP5TDwx1wheKv_8RK',#42,'386132|07KWWRP5TDwx1wheKv_8RK','Flow',#2221323,#1253092);
    #2221323= IFCDISTRIBUTIONPORT('0nZzcZ0J5DgflDttgLQWo0',#42,'OutPort_386132','Flow',$,#2221321,$,.SOURCE.,$,$);
    #1253092= IFCBUILDINGELEMENTPROXY('2Sqe7xoyHEagB9z$eWLJ8i',#42,'Urinal-Wall-3D:Urinal-Wall-3D:386132',$,'Urinal-Wall-3D',#1253091,#1253081,'386132',.USERDEFINED.);

The entity of type `IfcRelConnectsPortToElement` (#2221325) connects an entity of type `IfcDistributionPort` (#2221323) to an entity of type `IfcBuildingElementProxy` (#1253092). That is not allowed according to the standard. Instead of the reference to the `IfcBuildingElementProxy` enitity, there should be a reference to an entity of type `IfcDistributionElement` as 6th parameter ([specification](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcrelconnectsporttoelement.htm).

Most likely entity #1253092 could be replaced with the following to mitigate the error, but there may be more similar or different errors. Note that `IfcDistributionElement` has one parameter less then `IfcBuildingElementProxy`.

    #1253092= IFCDISTRIBUTIONELEMENT('2Sqe7xoyHEagB9z$eWLJ8i',#42,'Urinal-Wall-3D:Urinal-Wall-3D:386132',$,'Urinal-Wall-3D',#1253091,#1253081,'386132');

The erroneous data would have been valid in IFC2x3. There have been some changes in IFC4 around pipes and ports, so what you are experiencing here is probably related to the schema version update of either the data or the software. Apparently it was created with a version of the IFC exporter for Autodesk Revit 2015. This error may or may not be fixed in the meantime.

The above is just a quickfix which would not be sustainable, since there are more conceptual changes  for ports and the `IfcDistributionElement` type is deprecated. It will be made abstract in the future.

**Comment by JanoSlivka** [comment]
Thanks for explanation.

**Comment by hlg** [comment]
The URL scheme of the Auckland Open IFC Model Repository has changed and the file can now be found at: https://openifcmodel.cs.auckland.ac.nz/api/download/20160125OTC-Conference%20Center%20-%20IFC4.ifc
