### ISSUE TITLE
Maven https required

### ISSUE THREAD

**Issue by stoneman14** [opensourceBIM/BIMserver#1090]
Hello,
there is a problem with the installation of plugins with maven repos.
From today, https is required, so it must be changed everywhere in the source code. Otherwise it is impossible to install the plugins from the configuration at the start.

Thank you

![83564382_1394509830708843_2990224555814944768_n](https://user-images.githubusercontent.com/48518537/72470769-b0b45900-37e1-11ea-9384-75f5c58b34cc.png)

**Comment by rubendel** [comment]
Thank you! Will update asap.

**Comment by antoinediev** [comment]
Hu ruben, 

Do you know when a release will be available after this commit ? Thx

**Comment by rubendel** [comment]
I'll start one tomorrow.

**Comment by antoinediev** [comment]
Ok thx, and if I want to apply this change on an another previous version is it possible to rebuild the project myself and generate a .war file? I'm not a maven user/developer. Because I thinks this issue is impacting all versions when you are starting a fresh serveur. Thx ruben

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.181

You should be able to run a maven build of a previous version yes, just make sure the generated version number is the same because the plugins rely on that information.

**Comment by hlg** [comment]
For me, the fix did not work in all cases. I think only if the plugin version info was already found in my local maven repo. Otherwise I got different error messages depending on whether there was already something for that plugin or nothing. Not quite sure of the reason though, maybe also related to being behind a proxy. I got it working by replacing the Maven URL in few other places, e.g. the JSON requests in setup.html. I'll send a pull request.
