### ISSUE TITLE
-Xbootclasspath removed in Java 9

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#1118]
The -Xbootclasspath option has been removed from Java 9 onwards and thus running the BIMserver starter with a Java 9+ JVM and then specifying another JVM does not work anymore.

    Error occurred during initialization of VM
    java/lang/NoClassDefFoundError: java/lang/Object
    Error: Could not create the Java Virtual Machine.
    Error: A fatal exception has occurred. Program will exit.
    Unrecognized option: -Xbootclasspath C:\Program

I don't see a real use case for this setting. Why would you not use the same VM version to run the starter? Is it just to make point-and-click startup easy for people who are not able or allowed to control their environment?

**Comment by rubendel** [comment]
Yes from the beginning the JAR starter was designed to be very noob-friendly. Adding this feature was easier than explaining how to change the default JVM on each platform (or what a JVM is). I agree it makes more sense now to remove the feature of using another JVM altogether.

When we are on the topic of removing features from the JAR starter, there are a few more I think:
- Force IPV4, I don't think it has ever worked
- Proxy, same thing, don't think this ever worked for all outgoing connections in BIMserver, it's too much work to test as you need to setup a proxy server
- Stack size, at some point, all deep-recursion was removed from BIMserver, there is no need anymore to change the default stack size (people still do though because they are watching 10 year old youtube videos...)

What do you think?

**Comment by hlg** [comment]
As for the proxy, I had put in some effort to make this work in late 2019, perforce, to be able to use BIMserver in our university network. I am also running it on an internal application server behind the proxy. Not sure if this is testing enough, maybe we don't use some functionality that requires outgoing connections. As long as I work in this environment, I would certainly realize proxy-related issues sooner or later and could adopt this.

**Comment by hlg** [comment]
I think we should bring back the dereleased settings in the properties file (JarSettings.java). Even though they are not modifiable any more, if you use an older BIMServer version then a newer and again an older version, it would be great to still have those settings loaded. In addition we could preventively add default values in the `getProperty` calls here:
https://github.com/opensourceBIM/BIMserver/blob/61fd7e1b21ba4ea5d0f6b9a9e6227043e3b57a01/BimServerJar/src/org/bimserver/starter/JarSettingsProperties.java#L47-L53
Then, if later a property is removed, at least the default value will be set in the BIMserver starter.
