### ISSUE TITLE
User "last seen" field empty (null)

### ISSUE THREAD

**Issue by orwa84** [opensourceBIM/BIMserver#1123]
Hello,

I noticed that in the "bimvie.ws" frontend that as an admin, clicking "List Users" does not help show when each user was last logged in. Namely, that column always shows "never".

This includes the user that is currently logged in, and is the same when requesting this information through the Console.

Is this feature not implemented?

Thanks a lot for the great work on this software.

Orwa.

**Comment by rubendel** [comment]
This is disabled by default because it slows down the server when a lot of logins occur (usually due to badly written client-side code).

You can enable it in BIMvie.ws:
![image](https://user-images.githubusercontent.com/377978/76499503-208c3c00-643f-11ea-8ab1-aedd7c90ecfb.png)

Or with the API call:
```SettingsInterface.setServerSettings```
