### ISSUE TITLE
Can't install plugins for BIMServer 1.5.138

### ISSUE THREAD

**Issue by cherchor** [opensourceBIM/BIMserver#1133]
Hi,
I have tried to install the BIMServer 1.5.138 on Ubuntu 18.04. I can't install any plugin (bimviews, bimsurfer3, ifc plugins ...). It shows the following message: "No plugin bundle available for your version of BIMServer: org.opensourcebim...."
I really need your help. Thanks in advance.

**Comment by rubendel** [comment]
Why are you using such an old release?

**Comment by cherchor** [comment]
I am installing cmdbuild 3.2 and they are requiring this release.

**Comment by rubendel** [comment]
Ok that is unfortunate. Most older builds won't install anymore because of a changed URL for the plugins (on maven, not something we can change). There have been multiple issues about this, for exampe  https://github.com/opensourceBIM/BIMserver/issues/1095#issuecomment-580155764

**Comment by cherchor** [comment]
Thanks for your help. I appreciate. 
Keep up the good work ;)

**Comment by volubilis** [comment]
Hello I am having the same issue with tomcat/9.0.35 and Debian with version 1.5.182.  It shows the following message: "No plugin bundle available for your version of BIMServer: org.opensourcebim...." for all plugins

**Comment by MANTENIMIENTOSENA** [comment]
hello rubendel, I think that many users require version 1.5.138 as it is a complement to the bim installation in openmaint 2.0, could you solve this? We would appreciate it because Tecnoteca has not yet updated openmaint to the superior version of bimserver
these are the path that are required. regards

![image](https://user-images.githubusercontent.com/63219595/86550826-09e78480-bf09-11ea-974e-d69363346e60.png)

![image](https://user-images.githubusercontent.com/63219595/86550891-369b9c00-bf09-11ea-9748-4952ad5f323a.png)


> Ok eso es desafortunado. La mayoría de las versiones anteriores ya no se instalarán debido a un cambio de URL para los complementos (en Maven, no es algo que podamos cambiar). Ha habido múltiples problemas al respecto, por ejemplo [# 1095 (comentario)](https://github.com/opensourceBIM/BIMserver/issues/1095#issuecomment-580155764)

**Comment by hlg** [comment]
As Ruben said, this is **not** a BIMserver issue, but triggered by a change in Maven. BIMserver had reacted with these changes: a20ba03fc44366510a47f and 69b4b4d18317a9832159, which are included in developer release 1.5.182. You (or Tecnoteca for that matter) could create a maintenance branch for 1.5.138 and try to cherry-pick these two commits (if that is easier than upgrading to the latest release). We can not solve this on the BIMserver side. Official maintenance branches do only make sense for major releases. Otherwise we would have to patch every single developer release that someone might have in use.

**Comment by MANTENIMIENTOSENA** [comment]
I am trying to make your suggestion, but I must know the version of each bomserver plugin 1.5.138, I appreciate your help.

BIMvie.ws		V0.0.153
BIMsurfer 3		V0.0.237
Console			V0.0.38
IfcOpenShell		......?
IfcPlugins		        ......?
BinarySerializers	......?
glTF			        ......?
Default mergers	......?

**Comment by hlg** [comment]
I had a look at the Tecnoteca code. They released new versions of OpenMaint and CMDBuild in 09/2020, which still seems to use 1.5.138 (telling from the CMDBuild 3.3 sources). We can not do anything here, you have ask them through their support channel or forum. You can refer to this issue when you do so. They have two options: upgrade their client code to 1.5.182 or create a custom maintenance fork from 1.5.138 using the information above.
