### ISSUE TITLE
Get Geometry using the API

### ISSUE THREAD

**Issue by clementcolin** [opensourceBIM/BIMserver#1163]
I'm currently trying to download the geometry of a specific object using the API described in the console part.

I successfully checked in an IFC file along with its geometry, using BimServer 1.5.182.  
If I'm not wrong, the geometry is created when the IFC file is checked in and stored in the database as one big buffer. Each object can be retrieved thanks to the starting and ending vertex index. 

Two methods concerning the geometry in the API seems to be available: getGeometryInfo and getGeometryDataToReuse.
The first one returns some information on the geometry, such as the number of vertices, number of triangles, the bounding box... But I don't know how to use this information to actually get the geometry, i.e, the vertices.
I tried to use the second one, but I did not understand the result, as it returns a list of numbers. 

Is there a way to download the geometry of a specific object ? or the full geometry of one project ?

Thanks for the reply

**Comment by hlg** [comment]
I assume you are speaking about the triangulated geometry generated from the render engine, not the original IFC geometry.

You are partially right. Triangulated geometry is not stored as one big buffer, but multiple buffers, for vertizes, normals, triangle indexes etc. Have a look at [GeometryData.java](https://github.com/opensourceBIM/BIMserver/blob/master/PluginBase/generated/org/bimserver/models/geometry/GeometryData.java). Through the API, you can get the `GeometryData` OID from the `getGeometryInfo` response: it is provided in the `dataId` field. You could use the `LowLevelInterface.getDataObjectByOid` to access the geometry data and from there the buffers, but the byte buffer encoding is not transparent. I think there is no API call using the SBuffer class, which I assume would do base64 encoding.

To access triangulated geometry for whole revisions or queried subsets of revisions you would use a serializer which includes the geometry in the result. There are a binary serializers including geometry in the [BinarySerializers plugin](https://github.com/opensourceBIM/BinarySerializers), but the binary format is not very well-documented. You will have to make sense of it from the code or reverse-engineer serialization results. Alternatively, you can write your own serializer.

**Comment by clementcolin** [comment]
Thank you for your answer! 

I managed to get the indices of one object thanks to the first solution, using `LowLevelInterface.getDataObjectByOid`. 
First, I get the `GeometryData`, then, using the `dataId` field with `LowLevelInterface.getDataObjectByOid`, I can get the oid of the indices and vertices buffers. Using once again `LowLevelInterface.getDataObjectByOid`, I'm able to get those buffers as strings.

For those wondering, the buffers are stored in LittleIndian according to [this](https://github.com/opensourceBIM/BIMserver/blob/126039cc3388ccc5cc9649d5e0e7bd3544dc74d9/PluginBase/src/org/bimserver/utils/GeometryUtils.java) file. The indices one is an IntBuffer and the Vertices one is DoubleBuffer according to [this](https://github.com/opensourceBIM/BIMserver/blob/18821fd9f81e2f030477ab8a6a04f259642a5b79/BimServer/src/org/bimserver/TemporaryGeometryData.java) file. 

I started to try and get the indices first: I convert the string buffer to bytes to use it using `bytes(data, 'utf-8')`. Then I go through the data using `struct.iter_unpack('<i',arr)`. I managed to get the same number of indices as indicated in the `GeometryData`, so I assume this works fine.

But, I'm not getting the same amount of vertices as indicated in the `GeometryData` (nor the same amount, nor three times the amount since I assumed that I should recover 3 floats, x,y,x for the vertices). I assumed that it comes from the fact that the binary data is first encoded to base64 and then to string using UTF-8 (I was only able to find pieces of code like [here](https://github.com/opensourceBIM/BIMserver/blob/e519f6c0afd586148018742747e8a2a24a620be1/PluginBase/src/org/bimserver/emf/SharedJsonDeserializer.java#L548) ).  So I tried to use the `base64` python module after recovering the bytes from UTF-8, but I only found a few vertices. 

I'll try and get a look at your second solution in the future

**Comment by hlg** [comment]
I just tried it as well. There are two reasons for the length difference of the vertex buffer.

a) You need to unpack doubles. Even though in Python you use 8 byte floats, for iter_unpack you have to resort to the C data types with float for a 4 byte and double for an 8 byte floating point number.

b) The encoding is screwed. If I look at the escaped unicode string in the raw response for a vertex buffer, I see a couple of replacement characters: � `\xEF\xBF\xBD`. Because UTF-8 is a variable-width encoding, these are encoded as three bytes. Everything else (in my sample) is one byte, hence the byte array is twice the number of replacement characters longer than the string. If I check the string value length before unpacking, it has the right length.

I think the reason is in GetDataObjectByOidDatabaseAction, [where the encoding happens](https://github.com/opensourceBIM/BIMserver/blob/0081434424dafbe398bced8247e33650ae2454e8/BimServer/src/org/bimserver/database/actions/GetDataObjectByOidDatabaseAction.java#L164). Some byte sequences can never occur in UTF-8, those it may not be a good idea to do it this way. We should probably change this to base64.

**Comment by clementcolin** [comment]
I forgot to mention that I unpacked vertices as doubles, thanks for the explanation though. 

I also noticed that the encoding is screwed. I followed your intuition, and I replaced in [this file](https://github.com/opensourceBIM/BIMserver/blob/0081434424dafbe398bced8247e33650ae2454e8/BimServer/src/org/bimserver/database/actions/GetDataObjectByOidDatabaseAction.java#L164) the line : 

`dataValue.setStringValue(new String(((byte[])eGet), Charsets.UTF_8));` 

by

`dataValue.setStringValue(new String(Base64.encodeBase64(((byte[])eGet)), Charsets.UTF_8));`

and everything looks fine now, I'm able to get the buffers using the API calls. 

I don't know if this fix should be applied in other parts of the core code, nor if this change some expecting behaviour for plugins or other plugins. If not, I'll post that fix as a PR.

Thank you @hlg for the answers

**Comment by hlg** [comment]
You can also use `Base64.encodeBase64String((byte[]) eGet)` and drop the String constructor.

As far as I can see, this change would only have an impact in the `LowLevelInterface.getDataObject...` methods. Clients can't really rely on the flawed encoding because they wouldn't be reliably able to decode anything, unless for some data structure the original byte array was actually converted from an UTF-8 string, which I can't imagine. in that case the data model should have a string instead of a binary property.

I just realized that these API methods are already deprecated. It is not worth putting too much effort in fixing them. Also, if you work on some long-lived project, better don't rely on them.

**Comment by clementcolin** [comment]
Thanks for the advice.
I'll look forward to downloading the geometry using the download methods with the [BinarySerializers](https://github.com/opensourceBIM/BinarySerializers)
