### ISSUE TITLE
Can not export a jar or war from Eclipse

### ISSUE THREAD

**Issue by clementcolin** [opensourceBIM/BIMserver#1165]
Following [this](https://github.com/opensourceBIM/BIMserver/issues/1163) issue, I created an Eclipse project, as explained [here](https://github.com/opensourceBIM/BIMserver/wiki/Eclipse).
I'm able to run the project, with the `LocalDevBimServerStarter` main. 
However, I was unable to export a jar or a war. 
The only log that I have is some compiled warning, and in the Maven console : 
10/30/20, 5:13:45 PM GMT+1: [INFO] Resolving P/BimServer: org.opensourcebim:bimserver:1.5.183-SNAPSHOT with classifier null to /BimServer/target/classes
10/30/20, 5:13:45 PM GMT+1: [INFO] Resolving P/BimServerClientLib: org.opensourcebim:bimserverclientlib:1.5.183-SNAPSHOT with classifier null to /BimServerClientLib/target/classes
10/30/20, 5:13:45 PM GMT+1: [INFO] Resolving P/Shared: org.opensourcebim:shared:1.5.183-SNAPSHOT with classifier null to /Shared/target/classes
10/30/20, 5:13:45 PM GMT+1: [INFO] Resolving P/PluginBase: org.opensourcebim:pluginbase:1.5.183-SNAPSHOT with classifier null to /PluginBase/target/classes
10/30/20, 5:13:45 PM GMT+1: [INFO] Resolving P/Bdb: org.opensourcebim:bdb:1.5.183-SNAPSHOT with classifier null to /Bdb/target/classes
10/30/20, 5:13:45 PM GMT+1: [ERROR] Project Bdb classifier null resolved to wrong project at /Bdb/target/classes

Is there any documentation or solution in order to export the project as .jar / .war ?

**Comment by hlg** [comment]
We use Apache Maven for build automation. If you execute, for example, the Maven "package" goal, you will find the JAR in BimServerJar/target/, the WAR BimServerWar/target/. You may not want to run tests on every build, because they take very long. So for example, from the command line run `mvn -DskipTests=true package`.

I can't say much about Eclipse, but I know you can run Maven builds from within the IDE, maybe from the root project context menu? I also don't know how well the automatic incremental build and Maven build play together in Eclipse.

What did you do to get the above error? I can't reproduce it. Can you try to run a clean Maven build and see if the error persists?

**Comment by clementcolin** [comment]
It worked using Maven in the command line, `mvn compile` then `mvn package -DskipTests`. 
Thank you
