### ISSUE TITLE
Method setStringAttributeAtIndex fails with Attribute is not of type 'single'.

### ISSUE THREAD

**Issue by motjokk** [opensourceBIM/BIMserver#1166]
On BIMserver 1.5.182

Using method `setStringAttributeAtIndex` of the LowLevelInterface. 

`{"request":{"interface":"LowLevelInterface","method":"setStringAttributeAtIndex","parameters":{"attributeName":"AddressLines","index":0,"oid":17762096,"tid":26,"value":"New Address"}}}
`
<br>
Error msg: `UserException, Attribute is not of type 'single'` when committing the transaction.

**Comment by hlg** [comment]
Indeed, the low level interface calls did not get much attention, both in development as well as in using and testing it. I think they deserve some general cleanup and testing. There will be more issues surfacing. I also think the interface is incomplete. Keep this open as a reminder.

Out of curiosity: What are you using the low level calls for?

**Comment by motjokk** [comment]
I am trying to achieve full CRUD. So that attributes can be changed by the end-user through a web-front end. From what I see, the LowLevelInterface is the only way to go about doing this today. As a user, I rather like the functions, as long as they work.

**Comment by motjokk** [comment]
Hi @hlg again,

How is the interface working today, and how do you want to fix it? I have very little experience with Java development myself, but I might have a look at it.

**Comment by hlg** [comment]
I actually have an older fix for this particular issue in my fork (https://github.com/hlg/BIMserver/commit/af26a57e48fd7906e5e7710d8bd561518b0a1bdf?w=1), which needs a merge here.

Currently the attribute changes are implemented in the classes [SetAttributeChange](https://github.com/opensourceBIM/BIMserver/blob/f153f5192d816d1d934736563b510296827dfd89/BimServer/src/org/bimserver/changes/SetAttributeChange.java), [SetAttributeChangeAtIndex](https://github.com/opensourceBIM/BIMserver/blob/f153f5192d816d1d934736563b510296827dfd89/BimServer/src/org/bimserver/changes/SetAttributeChangeAtIndex.java) and [SetWrappedAttributeChange](https://github.com/opensourceBIM/BIMserver/blob/f153f5192d816d1d934736563b510296827dfd89/BimServer/src/org/bimserver/changes/SetWrappedAttributeChange.java) which are instantiated in the implementation of `LowLevelInterface`, [LowLevelServiceImpl](https://github.com/opensourceBIM/BIMserver/blob/f153f5192d816d1d934736563b510296827dfd89/BimServer/src/org/bimserver/webservices/impl/LowLevelServiceImpl.java). These contain some duplication and inconsistencies, probably from creation trough copy, paste and adjust. I would write some tests first and then refactor these classes.

The same may apply to other parts of the `LowLevelInterface`. I think it would be good to systematically go through all possible changes one may want to make and test whether it is possible with the current interface, ideally also writing unit tests. I thought I had a use case where I missed a call to set wrapped attributes at an index, but I can't find the note. I am not sure whether two-dimensional arrays are sufficiently covered or need adjustment.

It is great to see someone using the low level calls. You are very welcome to contribute if you still like to get your hands dirty with Java. Otherwise you help a lot if you just keep posting any other issues you encounter.

> that attributes and the ifc schema can be alterd as needed by the end-user

Do you really want users to alter the schema through your webapp or do just you mean to alter the structure, that is to add and delete entities, going beyond just changing attribute values?

**Comment by motjokk** [comment]
That sounds very good. The plan is to go beyond just changing values, and extend the schema. Consider the following example, where a IfcOccupant is added to a space. 
![Scan](https://user-images.githubusercontent.com/33512457/102989041-3cb42200-4515-11eb-9645-d80d982dbbbb.jpeg)

I think I`ll stick to reporting issues, since this seems most productive. 

Merry Christmas!
