### ISSUE TITLE
No geometry is shown 

### ISSUE THREAD

**Issue by yokoyamy** [opensourceBIM/BIMserver#1172]
**Describe the bug**

I can' t see any geometries in the `3D` tab  although I can see many of IFC entities in `browser`  tab.

**To Reproduce**
Deploying  bimserverwar-1.5.182.war
Setup bimserver
Creating new project.
Selecting Check In
`Choose file`  and   `Checkin new revision`
Generating geometry process seemed successfully finished

 
**Expected behavior**
I expected geometry will be shown in `3D` tab .

**Screenshots**
If applicable, add screenshots to help explain your problem. Please do not create screenshots of log files etcetera, copy and paste the actual text.

**Additional context**

**Comment by hlg** [comment]
Please provide more information: Are you sure this file contains geometry? Which plugins have you installed? Does this only happen in an application server with the war file or also with the jar when you run it locally? Do you see any errors in the BIMserver log or your browser's javascript console?

**Comment by yokoyamy** [comment]
I use IFC-files from following site.
https://github.com/opensourceBIM/IFC-files/blob/master/HHS%20Office/MEP.ifc

My plugins are
```
 BIMvie.ws
 BimSurfer
 BinarySerializers
 Console	
 DemoPlugins
 FixedFileService
 IfcAnalyses
 IfcAnalytics
 IfcOpenShell-BIMserver-plugin
 IfcPlugins 
 Mergers
 OAuthClientTest
```
I user bimservewar-1.5.181 

No error in server log(bimserver.log) but an error in  bowser console.

`DevTools failed to load SourceMap: Could not load content for http://mydomain/bimserverwar-1.5.181/apps/bimviews/deps/bimsurfer-v1/lib/hammer/hammer.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`
`

**Comment by hlg** [comment]
We can not reproduce the issue. The geometry shows up fine, at least with the 1.5.182 jar version. Can you please check with this version as well, such that we can proceed to isolate the source of your issue?

![20201207_mep-geometry_s](https://user-images.githubusercontent.com/356986/101347400-52291b00-388a-11eb-95d2-5831ff369ece.PNG)

Can you display other IFC files in the 3D view or is it a general issue? Please confirm you can show the [buildingSMART Wall with window sample](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/wall-with-opening-and-window.htm) as a minimal example.

**Comment by yokoyamy** [comment]
Thank you for yore response.

I tried ifcwindow-esample [https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/annex/annex-e/wall-with-opening-and-window.ifc](url)

However, the geometry isn't shown yet.

I use google chrome as the browser, and its version is  87.0.4280.141.

![Screen1_3Dtab](https://user-images.githubusercontent.com/11791858/105000404-a15d9080-5a71-11eb-88af-23314ee942f1.png)
![Screen2_Browsetab](https://user-images.githubusercontent.com/11791858/105000408-a1f62700-5a71-11eb-8e59-ec5912add90f.png)

**Comment by yokoyamy** [comment]
I can see tow types of  error message on the browser console when I click the link-text in the tree.


```
bimserverapipromise.js:69 Uncaught TypeError: Cannot read property 'isDone' of undefined
    at bimserverapipromise.js:69
    at Array.forEach (<anonymous>)
    at BimServerApiPromise.chain (bimserverapipromise.js:68)
    at Project.loadDetails (eval at globalEval (bimviews.js?_v=0.0.182:338), <anonymous>:507:12)
    at eval (eval at globalEval (bimviews.js?_v=0.0.182:338), <anonymous>:39:12)
    at bimserverclient.js:962
    at bimserverclient.js:713
    at XMLHttpRequest.xhr.onload (bimserverclient.js:587)

```

```
VM55:62 Uncaught TypeError: object.getGeometry is not a function
    at Properties.selected (eval at globalEval (bimviews.js?_v=0.0.182:338), <anonymous>:62:11)
    at eval (eval at globalEval (bimviews.js?_v=0.0.182:338), <anonymous>:49:4)
    at Array.forEach (<anonymous>)
    at EventRegistry.trigger (bimviews.js?_v=0.0.182:16835)
    at Project.selected (eval at globalEval (bimviews.js?_v=0.0.182:338), <anonymous>:48:25)
    at Node.ProjectTree.treeItemClick [as onClick] (eval at globalEval (bimviews.js?_v=0.0.182:338), <anonymous>:267:11)
    at Node.linkClick (bimviews.js?_v=0.0.182:15444)
    at HTMLAnchorElement.dispatch (bimviews.js?_v=0.0.182:4732)
    at HTMLAnchorElement.elemData.handle (bimviews.js?_v=0.0.182:4544)

```

**Comment by hlg** [comment]
These errors can appear when you select something in the tree while not having the 3D tab open. In BIMvie.ws (remember it is just a demo application) tree selection only works in connection with the 3D view.

I am wondering why you are having BIMvie.ws 0.0.182 installed? For BIMserver 1.5.182, you should have 0.0.184 as latest BIMvie.ws version. It does not matter with regard to BIMvie.ws, because there have not been changes since 0.0.182, but are you really using BIMserver 1.5.182 (jar) with all other plugins in their latest version?

You can also try the following:

1. When in 3D view, reload with F5 or Ctrl-R and switch the eye symbol off and on again. Sometimes it's just a browser hickup.
2. Do you have geometry generated? Go to _Extended Data / Geometry generation report (text/html)_. Then check that _IFC Model / Triangles_ is larger than 0 and _Render engine / Render engine name_ is not "NOP Render Engine".
3. If there is no render geometry and NOP render engine in step 2, go to _User settings / Render Engines_, select "IfcOpenShell" as the default and then checkin again.

**Comment by yokoyamy** [comment]
I Deployed bimserverwar-1.5.181.war 

1.I did. But nothing haven't changed.
2.Extended Data / Geometry generation report (text/html) is `2`.
    There isn't  IFC Model / Triangles 
     There isn't   Render engine 
3. There are IfcOpenShell and  NOP Render Engine. IfcOpenShell is set as Defalutl`.

**Comment by hlg** [comment]
> Extended Data / Geometry generation report (text/html) is `2`.

What does that mean? If there is a report, you can open the report and should see something like the below. It tells you whether geometry generation on checkin was successful and you will find the render engine used and the number of triangles generated.

You can browse extended data by revision. There may be no report for a revision when  you checked in without geometry generation or there may be more than one when you regenerated geometry.

<h1>BIMserver geometry generation report (v1.2)</h1>
<h3>Render engine</h3>
<table><tbody>
<tr><td>Render engine name</td><td>IfcOpenShell</td></tr>
<tr><td>Render engine version platform</td><td>linux64</td></tr>
<tr><td>Render engine version branch</td><td>v0.6.0</td></tr>
<tr><td>...</td><td>...</td></tr>
</tbody></table>
<h3>IFC Model</h3>
<table><tbody>
<tr><td>File name</td><td>wall-with-opening-and-window.ifc</td></tr>
<tr><td>File size</td><td>11.80 KB</td></tr>
<tr><td>Schema</td><td>IFC4</td></tr>
<tr><td>Objects</td><td>203</td></tr>
<tr><td>Triangles</td><td>56</td></tr>
<tr><td>Triangles including reuse</td><td>0</td></tr>
</tbody></table>
<h3>... </h3>
<h3>Jobs</h3>
<table><thead>
<tr><th>Main type</th><th># objects</th><th>Uses mapping</th><th># triangles</th><th>Total time</th><th>CPU time</th><th>Max memory</th><th>Exception</th><th>Debug file</th></tr>
</thead><tbody>
<tr><td>IfcWall</td><td>1</td><td>false</td><td>32</td><td>275ms</td><td>0ms</td><td>0</td><td>None</td><td>None</td></tr>
<tr><td>IfcOpeningElement</td><td>1</td><td>false</td><td>12</td><td>140ms</td><td>0ms</td><td>0</td><td>None</td><td>None</td></tr>
<tr><td>IfcWindow</td><td>1</td><td>false</td><td>12</td><td>233ms</td><td>0ms</td><td>0</td><td>None</td><td>None</td></tr>
</tbody></table>
<h3>Processing</h3>
<table><tbody>
<tr><td>Start</td><td>04-02-2021 09:05:08</td></tr>
<tr><td>Stop</td><td>04-02-2021 09:05:08</td></tr>
<tr><td>Total time</td><td>397ms</td></tr>
</tbody></table>
<h3>Geometry</h3>
<table><thead>
<tr><th>Type</th><th>Used</th></tr>
</thead><tbody>
<tr><td>IfcExtrudedAreaSolid</td><td>3</td></tr>
<tr><td>IfcPolyline</td><td>1</td></tr>
</tbody></table>
<h3>Debug files</h3>
<table><thead>
<tr><th>ID</th><th>Filename</th></tr>
</thead><tbody></tbody>
</table>

**Comment by yokoyamy** [comment]
I meant 
![image](https://user-images.githubusercontent.com/11791858/107015593-41404b80-67e0-11eb-92ff-f35e0be7128c.png)

How to get  `BIMserver geometry generation report`?

**Comment by hlg** [comment]
In project view, where you have the row of tabs starting with _3D_, got to the tab _Extended Data_, it is just left of the _Browse_ tab.

**Comment by yokoyamy** [comment]
Thanks, I updated  previous post.

**Comment by hlg** [comment]
This looks as if your IfcOpenShell binary is corrupted. The binary is downloaded during plugin installation. A while ago, I have observed very slow response from the server hosting IfcOpenShell and subsequently timeouts during download. Maybe your BIMserver instance has been affected by this as well or experienced other issues that resulted in corruption of the binary. Let's see if the the following will solve the issue.

In the BIMserver home folder, look at the folder tmp/org.opensourcebim.ifcopenshellplugin. There should be a file with name IfcGeomServer-v0.6.0-b4ce5be-linux64 and a size of 24630528 bytes. If it is there, but has a smaller size, this is our culprit. You want to delete this file (or rename it), in order to be able to initiate a new download by reinstalling (first uninstall, then install) the IfcOpenShell plugin. Instead of reinstalling, you can also open the plugin settings (_Server / Installed Plugin Bundles / IfcOpenShell-BIMserver-plugin / Plugins / IfcOpenShell_) and save them without changing anything. Both methods should cause the plugin's init method to execute and download the binary.

**Comment by yokoyamy** [comment]
Mine is 24630528.

But I  reinstalled.

Now Check in doesn't start its process.

![image](https://user-images.githubusercontent.com/11791858/107106704-25848600-6870-11eb-8746-dc7e21ad3e3c.png)

**Comment by hlg** [comment]
Why are you using bulk checkin? Please try with regular checkin.

**Comment by yokoyamy** [comment]
I did regular checkin. 
However, nothing is changed .Still no geometries.

**Comment by hlg** [comment]
I just realized this looks similar to #1147  and #633, with solution in this comment: https://github.com/opensourceBIM/BIMserver/issues/633#issuecomment-341644945. Can you have a look?

**Comment by yokoyamy** [comment]
I updated gcc and  libstdc++ and solved.
Thank you so much.

**Comment by 252651980** [comment]
![image](https://user-images.githubusercontent.com/16971362/152950760-74081ce9-e758-4bd8-8694-e6b736d28e6d.png)
Dear sir,
I also have this issue. It looks like the json is empty so that 'if (!promise.isDone) {' will be 'Cannot read properties of undefined'. But the json is generated by uploading ifc file.
