### ISSUE TITLE
Why 3d model is not updating upon using setDoubleAttribute console api?

### ISSUE THREAD

**Issue by Abhicode5** [opensourceBIM/BIMserver#1173]
Here is a description of problem faced 

I loaded an ifc file in the bimServer . I am able to see the rendered 3d model. Then i used the console setDouble api to change the overallWidth or OverallHeight of the ifc file component (say ifcWindow) . The  new changes are reflected when i see the file downloaded as json object  and also in the "BROWSE" tab (i.e new overallWidth is say changed from 2.0 to (100 or any other value)).

But why is not window width extended in the 3d model to account for new changes ? It is still same as the initial model.
I also tried regenerating geometry using IFCopenShell and also setting attribute regenerate geomtery to true but nothing seems to be working. 

Please help me if you know anything .
Thanks

**Comment by hlg** [comment]
If you want to use the low level interface, you need to be very familiar with the IFC specification. It is similar to editing an SPF file with a text editor or only slightly safer because you cannot break the syntax. But you may still introduce semantic inconsistencies into the model. In your example, you did not change the representation, thus the changes don't affect the 3D view.

Have a look at your changed IFC data with a different 3D viewer to confirm that this is not an IfcOpenShell or BIMsurfer issue. You can also verify successful geometry generation from the geometry report in extended data.

**Comment by Abhicode5** [comment]
Hi @hlg  thanks for giving your precious time to help me , really appreciate it .
I dont know much about the BimServer and Ifc in general . Just started using it .

 I have the following issue to be precise.

My input :  loaded an ifc file of a small house with say 5 windows ,2 doors  and other things into  the bimServer.
Initial configuration:    initially the model has some object properties like ifcwindow with specific height and width attribute.

Like this : 

ProvidesBoundaries | IfcRelSpaceBoundary (1CHFwsKi9DzPwVCoK7udjt)

ConnectedFrom |  
ContainedInStructure | IfcRelContainedInSpatialStructure (0XHFH9CC90WRFZ4wD4NsBG)
OverallHeight | 1.7
OverallHeightAsString | 1.7
OverallWidth | 2
OverallWidthAsString | 2.

Final Goal :  Using console api setDoubleAttribute on "specific window id or object id " say 1234 . change the attribute "overallHeight from 1.7 to say any value - 3.0 for eg.".  And when rendering it i want the window id no 1234 height to be increased from 1.7 to 3.0. ( i.e final goal is to take any object with an id - modify its size and render 3d model to see changes )

What i have done :  Using console api - setDoubleattribute , i am able to change parameter of obj id 1234 - overallheight from 1.7 to say 3.0.  Confirmation of change 👍 
1. - IN bimServer under 'BROWSE' tab i see under ifcWindow with oid 1234 it shows the updated change. 
2. Also i use query method  - (ifcProduct) - i download the object as Json i search with the id 1234 and attribute OverallHeight shows the change 1.7 to 3.0 for that object.

Problems:
1.  the BimServer 3d model doesn't change it is same as initial loaded model.
2.  After Quering the updated model i downloaded it in a giTf format and used other viewer tools but they also doesn't show any change i.e same as original :(   ( why gitf and not ifc? - because i am facing an issue while downloading it in a ifc format - i get empty model . but in giTf i get a proper model file).
3. in Bimserver there is an option to REGENERATE GEOMETRY using ifcOpenShell  - also used that but no change in 3d view.

Am i doing something wrong or is this a bug in BimServer ( i use console api to set value and see the model using bimvie.ws)
How can i  achieve my goal? 

Thanks

**Comment by hlg** [comment]
No, the unchanged 3D view is not a bug in BimServer. The `OverallHeight` attribute does not affect the shape representation of the window and is subsequently not supposed to change the triangulated geometry when regenerating nor affect the visual 3D representation. The only effect that you achieve by changing this attribute is that your model becomes somewhat inconsistent. You need to study the semantics of the IFC schema if you want to be able to manipulate geometry. But be warned that the specifications in the geometry resource are fairly complex. Once you got that sorted out, you should be able to achieve what you want through the API, for example through the Console application.

This issue tracker is not a good place to teach and learn IFC, because it is meant mainly to report BIMserver bugs and to a lesser extent to discuss and track new features and enhancements. The documentation at [buildingSMART technical](http://technical.buildingsmart.org), the [bS forums](http://forums.buildingsmart.org) and the [IFC tag at StackOverflow](https://stackoverflow.com/questions/tagged/ifc) may all be good places to start reading. If you want to ask questions in any of these places, please make sure to research whether your question has already been answered.

The empty IFC download could be a bug though. In case you think it is, please provide additional information: Which version are you using? Which steps did you take to download? Are there any errors in the log? Is it empty only for this particular IFC file / project / revision or for any download?
