### ISSUE TITLE
How to find Relation between a Switch and a wall?

### ISSUE THREAD

**Issue by Abhicode5** [opensourceBIM/BIMserver#1175]
I want to check if a specific wall with ifcwall obj id 123 has a switch or not ?  and if yes the object id of that switch

Can this be achieved using Console api? or any other programatic method?

& how to find associations in general i.e which 4 walls are associated to each other that makes up a room?

**Comment by hlg** [comment]
Same as [your other question](https://github.com/opensourceBIM/BIMserver/issues/1173), this is a question about the IFC schema rather than a BIMserver issue. Once you got the details of the schema sorted out, you should be able to achieve what you want through the API, for example through the Console application or using a client library in your language.

This issue tracker is not a good place to teach and learn IFC, because it is meant mainly to report BIMserver bugs and to a lesser extent to discuss and track new features and enhancements. The documentation at [buildingSMART technical](http://technical.buildingsmart.org), the [bS forums](http://forums.buildingsmart.org) and the [IFC tag at StackOverflow](https://stackoverflow.com/questions/tagged/ifc) may all be good places to start reading. If you want to ask questions in any of these places, please make sure to research whether your question has already been answered before.
