### ISSUE TITLE
Unable to generate a war

### ISSUE THREAD

**Issue by spieza4u** [opensourceBIM/BIMserver#1258]
Hi everyone,

I maded some change to html and js files, but now I have some issue trying to generate a war file to execute with Tomcat.
I can execute the project with Eclipse without errors.
Anyone can help with some wiki or a guide on how to configure and compile the project?

Thank you all

**Comment by hlg** [comment]
We use Apache Maven for build automation. If you execute, for example, the Maven "package" goal, you will find the JAR in BimServerJar/target/, the WAR in BimServerWar/target/. You may not want to run tests on every build, because they take very long. So for example, from the command line run `mvn -DskipTests=true package`.

I can't say much about Eclipse, but I know you can run Maven builds from within the IDE and also configure it to skip tests. Please feel free to add a further comment with documentation for future reference if you know more about it.

Actually, this question has already been asked and answered before: #1165.

**Comment by dariochianetta** [comment]
I had the same issue. I updated jdk 8 to jdk 11 & Tomcat to 9V. Then I compiled by maven command: mvn clean install.
All worked fine.
