### ISSUE TITLE
Login token lifecycle

### ISSUE THREAD

**Issue by michelespinella** [opensourceBIM/BIMserver#1263]
**Describe the bug**
Not a bug a clarification about the lifetime of a token obtained by login Rest Service

**To Reproduce**
1. Go to 'console'
2. Click on 'login'
3. Input the username and password
4. See response with token 

**Additional context**
How many hours or minutes the token obtained by login takes to expire?

**Comment by hlg** [comment]
Currently, it does not expire, not even on logout. See #884.

**Comment by michelespinella** [comment]
Good day,
   thanks.
I am building a bimserver client, a microservice that wrap bimserver API an process IFC files, all on top of bimserver.
In this case I will manage the lifecycle of the token on my service, is correct this approach?
Thanks and regards
Michele SPinella

**Comment by hlg** [comment]
If you put your own application or service in front of BIMserver, you have to keep and manage tokens. If you use the JSON API, your service acts as a client towards BIMserver and you can look at other clients - they all do it this way. No need to pass the token further outside. You could also do your own user management and work with just one  BIMserver account for your service. That's what Ruben recommended, because user management is not very advanced: #732.

**Comment by michelespinella** [comment]
Thanks a lot for clarifications. I will design all in this way:

Keycloak<-myservice with bimserverclientLib->Bimserver

But does bimserverclientLib implements all the method of the bimserver console?

Thanks and regards
Michele Spinella

**Comment by hlg** [comment]
You can access all interfaces and call all interface methods through the Java client in the client lib, same as through the console. Be aware that the client aims to do a bit more than that and has some issues related to this additional functionality, namely hold a (partial) copy of a model in memory (see issue list). If you just need the interfaces, that should be fine though. You could also just use the client lib code for inspiration to write your own or are welcome to contribute to improvements.
