### ISSUE TITLE
Two IFC 2x3 files do not match

### ISSUE THREAD

**Issue by cvc-ru** [opensourceBIM/BIMserver#1281]
Two IFC 2x3 files do not match.
In other programs (Autodesk NavisWorks and BIMVision) - the same. 

bimserverjar-1.5.182
Google Chrome 98.0.4758.102

Small project
![image](https://user-images.githubusercontent.com/48197753/203519035-5fd1d5a5-6a43-426d-9194-5201bc0e3067.png)
If you turn on the visibility of both elements, only one will be visible. The second element will be in a different location.
In BIMVision they are close by
![image](https://user-images.githubusercontent.com/48197753/203519756-da9b34b8-bcc7-4029-8034-56293ddc2ee3.png)

I post 2 files with examples
Is this a bug in the program or am I doing something wrong?

[DTP.zip](https://github.com/opensourceBIM/BIMserver/files/10074410/DTP.zip)
[PartOfBrigde.zip](https://github.com/opensourceBIM/BIMserver/files/10074411/PartOfBrigde.zip)

**Comment by hlg** [comment]
I am not totally clear on what's wrong with this - the files themselves or something in the process of storing, retrieving and finally displaying the two projects together. They differ in various ways with regard to how elements are positioned, for example one has length measures in millimeters, the other in meters. Also one has WGS 84 coordinates, the other one has not. Given the different length units, the placement coordinates seem to be roughly in the same range.

**Comment by cvc-ru** [comment]
These files are created in two different programs. The bridge was made in Autodesj Revit, and the road in Topomatic Robur. And in the programs for viewing the IFC, the road and the bridge are joined. I tried the variant and IFC v2x3 and v4.
I attached the nvd file from Autodesk Navisworks - as it should be.
[project.zip](https://github.com/opensourceBIM/BIMserver/files/10091013/project.zip)

Does Bim Server look at geographic coordinates? It doesn't place objects X Y Z?

**Comment by hlg** [comment]
As I said, at the moment I can't tell from the top of my head whether the reason is in the file itself (or the export from authoring software accordingly) or in the downstream IFC processing chain leading to the wrong display (BIMserver, BIMvie.ws, IfcOpenShell ...). I just did a quick analysis and listed a couple of differences that appear as potential sources for the issue.

**Comment by zaqifathis** [comment]
Hi @cvc-ru , I have reproduced your issue and I also tried to double check with other example as well :
https://github.com/buildingSMART/Sample-Test-Files/tree/master/IFC%202x3/Medical-Dental%20Clinic

First of all, the issue is likely due to different length unit (millimeters and meters). Therefore, I guess the issue could happened in the following places:
- During streaming geometry information/data. \
If I am correct, the geometry information from the ifc files will be triangulated using selected render engine (default: IfcOpenShell) and all the information related to the geometry(e.g., vertex position, color, ..) will be saved to the database. Here, the unit will be checked and if it is different from the project unit, it will be scaled accordingly.

- During rendering in BIMvie.  \
The information that saved in the database then send to BIMvie for actual rendering (so you can see your 3d model). Here, it might be that the model is scaled again.

**Comment by zaqifathis** [comment]
The issue did not show up anymore in the latest commit `8023775`
