### ISSUE TITLE
Use BimSuffer have an error

### ISSUE THREAD

**Issue by victor-freedom** [opensourceBIM/BIMserver#1292]
15:17:48 ERROR [org.bimserver.ServiceInterface.download]:                                                                                  (LongStreamingDownloadAction.java:213) 
org.bimserver.database.queries.om.QueryException: Class "IfcRelDecomposes" does not have the field "RelatedObjects"
	at org.bimserver.database.queries.om.Include.addField(Include.java:93)
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.parseInclude(JsonQueryObjectModelConverter.java:372)
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.processSubInclude(JsonQueryObjectModelConverter.java:567)
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.parseInclude(JsonQueryObjectModelConverter.java:411)
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.parseDefines(JsonQueryObjectModelConverter.java:313)
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.parseJson(JsonQueryObjectModelConverter.java:258)

I used bimsuffer to read the object  by IFC4 format , and then ,the server has the error .
what's the problem?
bimserver is 1.5.184
bimsuffer used xeoviewer

**Comment by hlg** [comment]
Assuming you are talking about [the old BimSurfer](https://github.com/opensourceBIM/BIMsurfer-before2019), this seems to be due to a change between IFC2x3 and IFC4, where the attribute `RelatedObjects` was demoted to (selected) subtypes of `IfcRelDecomposes`, e.g.  to `IfcRelAggregates`. Thus, the query that xeoviewer obviously uses ([PreloadQuery.js](https://github.com/opensourceBIM/BIMsurfer-before2019/blob/12246d89de08ed789301303d059a90287e9e5cb4/bimsurfer/src/PreloadQuery.js) or [BimServerModel.js](https://github.com/opensourceBIM/BIMsurfer-before2019/blob/12246d89de08ed789301303d059a90287e9e5cb4/bimsurfer/src/BimServerModel.js)) is not valid for IFC4 anymore. This issue would belong to the BIMsurfer repository, but you can not expect for it to be resolved, since the old BIMsurfer is not maintained anymore.

**Comment by victor-freedom** [comment]
Thank you
I will try to use IFC2x3&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opensourceBIM/BIMserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月21日(星期五) 晚上8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opensourceBIM/BIMserver] Use BimSuffer have an error (Issue #1292)





 
Assuming you are talking about the old BimSurfer, this seems to be due to a change between IFC2x3 and IFC4, where the attribute RelatedObjects was demoted to (selected) subtypes of IfcRelDecomposes, e.g.  to IfcRelAggregates. Thus, the query that xeoviewer obviously uses (PreloadQuery.js or BimServerModel.js) is not valid for IFC4 anymore. This issue would belong to the BIMsurfer repository, but you can not expect for it to be resolved, since the old BIMsurfer is not maintained anymore.
