### ISSUE TITLE
Create serializer with Density design

### ISSUE THREAD

**Issue by berlotti** [opensourceBIM/BIMserver#133]
Just because it   is cool....
Please create a BIMserver serializer plugin with  the tools from: http://app.raw.densitydesign.org/
For example:  analyse an IFC model  (example in attachement from https://twitter.com/StijnvanSchaijk/status/522775445025353728 
![b0fffk2iqaa52z3](https://cloud.githubusercontent.com/assets/356921/4665666/ae8421e2-554c-11e4-9c44-f4d40834f6b0.png)
![b0fffveiyaayle8](https://cloud.githubusercontent.com/assets/356921/4665667/ae88c9fe-554c-11e4-91db-5a1f32dcf662.png)
![b0fffwgiyaahea1](https://cloud.githubusercontent.com/assets/356921/4665668/ae9af944-554c-11e4-8785-02b3f82c8116.png)

**Comment by lirmont** [comment]
I've ported RAW to be a Java-based server-side library. You can check the code out here: https://github.com/lirmont/BIMserver/tree/master/Charting

__IFC Treemap by Area__

![treemap - product by area](https://cloud.githubusercontent.com/assets/811142/5898445/91358c2c-a51d-11e4-8a4d-b9a49843b118.png)

__IFC Circle Packing by Area__

![circle packing - product by area](https://cloud.githubusercontent.com/assets/811142/5898447/9583f8fe-a51d-11e4-8ffa-079fc92542f3.png)

More plugins for charts can be added. All the charts in RAW have been ported or otherwise provided for. I just lack the industry knowledge to know what to go looking for. For example, if you know of something in IFC that is based over time with a value, that can be used to make a plugin to generate bump charts. If there's something in IFC that documents required building material (like cement) for a particular IfcProduct, that can go into a plugin to generate alluvial diagrams. Et cetera.

Other non-plugin examples might be to provide visualizations for BIMserver internals (like usage data over time).

Thanks.

**Comment by berlotti** [comment]
Would be nice to see the number of objects per classification. 
Every product in IFC can have a classification. Giving an overview of how many objects of what classification are in a model would be great.

Same for material. How many m2 or m3 meters of a material are in a model.

**Comment by lirmont** [comment]
For IFC classifications, something like one of the ones in the image? Materials are next, but will require research on my part.

![ifc class count](https://cloud.githubusercontent.com/assets/811142/5992189/78ca928a-a9ec-11e4-8d80-6390b337e935.png)

**Comment by berlotti** [comment]
Google on "ifc classification" for more info. 
E-mail me on leon.vanberlo@tno.nl for models with classification examples.

**Comment by lirmont** [comment]
Found one online with classifications.

![a](https://cloud.githubusercontent.com/assets/811142/5994131/5551e50c-aa36-11e4-83cf-d32fe7e6803b.png)

![b](https://cloud.githubusercontent.com/assets/811142/5994133/58aed7c8-aa36-11e4-8635-14d3396211ac.png)

**Comment by lirmont** [comment]
I've added material usage charts, and I think this issue is thoroughly solved. New issues can be made for exploring the idea of adding other specific charts. Thanks.

![material-usage-same-scale](https://cloud.githubusercontent.com/assets/811142/6026893/4a7f2118-abac-11e4-959e-1e4163117043.png)

**Comment by mrca** [comment]
Hello @lirmont, I am trying out the bimserver, at the moment running locally from the jar installer in a Windows server. I would like to try your serializers, so far I have created a jar from the Charting folder using JDK and copied it to the plugins folder, the server starts fine (no complains) but the plugin is not showing up once the server is restarted. How do I get it to work? Do you have a working .jar to deploy on an installer BS? Thanks for the help and great job!

**Comment by lirmont** [comment]
@mrca, it's designed to work with the __master__ branch of BIMserver's main repository. You'd compile everything into a JAR (similar to the one you're using now) by using the __Builds__ project's "Build Jar" ANT build task in _build.xml_. I don't know what determines backwards compatibility; I just know it works for me if I use that task to create an expanding JAR or have Eclipse run _LocalDevBimServerStarter_ (faster).

Anyway: http://darkabstraction.com/showOff/bim/bimserver-${version}-charting.jar

Thanks.

**Comment by berlotti** [comment]
Hi @lirmont. I am closing this issue indeed. Job well done and thank you so much!
What I intended with the material question was an overall view of the materials in the whole model (so not per object). In this case a contracter would get an idea of the amount of steel, concrete, etc in a building. 

Another interesting chart would be to get the data from the "LOD Checker"  and visualise that (number of triangles per m3, number of objects per m3, number of attributes per object, etc). This would give an idea of the detailness (is that a word?) of a model.

From Stijn van Schaijk (the guy who made the original pictures that started this issue) I heard that he is interested in the visualisation of the progression over time. So number of objects over all revisions of a model in BIMserver.

Just see if you get inspired by this :-)
