### ISSUE TITLE
1.3.6-FINAL-2015-01-31 missing streaming servlet 

### ISSUE THREAD

**Issue by dlabz** [opensourceBIM/BIMserver#170]
Win7 x64
JDK 1.8.0_25-b188
tomcat 7.0.57

When deployed in a fresh install, BIMserver shows setup as usual and installs, but on load BimViews crashes, as ws://localhost:8080/stream returns 404/page not found.

catalina.log and bimserver.log didn't show any errors.

Turns out \ROOT\WEB-INF\web.xml is missing whole piece of code:
```
	<servlet>
		<servlet-name>StreamingServlet</servlet-name>
		<servlet-class>org.bimserver.servlets.TomcatStreamingServlet</servlet-class>
		<load-on-startup>1</load-on-startup>
	</servlet>
	<servlet-mapping>
		<servlet-name>StreamingServlet</servlet-name>
		<url-pattern>/stream/*</url-pattern>
	</servlet-mapping>
```

After manually editing the web.xml inside ROOT.war, it seems to work.

**Comment by rubendel** [comment]
This is a bit more complicated. The WAR build is actually for the latest version of Tomcat, which is Tomcat 8. Tomcat 8 uses JRS-356, which registers a websocket handler by using Java annotations instead of an entry in web.xml. I will add the Tomcat7 build to the build system as well.

It's a pain in the ass to be creating different war files for different versions of application containers, but that's unfortunately the only way because Tomcat8 does explicitly not support the old way of using web sockets.

**Comment by dlabz** [comment]
Funny enough, unzip-edit-zip got it fully working.

**Comment by rubendel** [comment]
Yes I know, but with that edit it won't work in Tomcat 8

**Comment by dlabz** [comment]
Well, in tomcat8 it would have worked without this dirty hack...

**Comment by rubendel** [comment]
So you agree we need 2 different builds then?

**Comment by rubendel** [comment]
Tomcat7 build added to release build
