### ISSUE TITLE
extend Charts serializer plugin

### ISSUE THREAD

**Issue by berlotti** [opensourceBIM/BIMserver#173]
Extend the 'charts serializer' plugin with:
- overall view of the materials in the whole model (not per object). In this case a contracter would get an idea of the amount of steel, concrete, etc in a building.

- Another interesting chart would be to get the data from the "LOD Checker" and visualise that (number of triangles per m3, number of objects per m3, number of attributes per object, etc). This would give an idea of the detailness (is that a word?) of a model.

- From Stijn van Schaijk (the guy who made the original pictures in issue #133 ) I heard that he is interested in the visualisation of the progression over time. So number of objects over all revisions of a project in BIMserver.

**Comment by lirmont** [comment]
Raw materials:

![raw-mat-full](https://cloud.githubusercontent.com/assets/811142/6090867/691a05ce-ae5a-11e4-80d2-be85e56fa4fd.png)

Level of detail metrics:

![lod](https://cloud.githubusercontent.com/assets/811142/6090870/8bde002e-ae5a-11e4-96d8-759f3e0ee38c.png)

Off-topic: "detailedness" (like "signedness" for +/-).

I will apparently have to look up service plugins to accomplish that third one, since the EmfSerializer class fast-forwards to after the revision is already picked.

**Comment by lirmont** [comment]
I don't know if I'll check this particular serializer plugin in, considering it required a change to the BimServer base (i.e. the change specifically is to provide the revision ID through the project info object handed to all serializers). In addition to that, it does questionable things to get back to a point where it can ask for and retrieve all the revisions of a project. But, it does work.

__Changes Only__
![delta](https://cloud.githubusercontent.com/assets/811142/6111026/d0258ad6-b053-11e4-9fd8-7112eb91c515.png)

__Changes from Zero__
![delta-zero](https://cloud.githubusercontent.com/assets/811142/6111027/d19efc08-b053-11e4-8602-6127d734bf2b.png)

__Whole Values__
![whole-value](https://cloud.githubusercontent.com/assets/811142/6111029/d2fa8496-b053-11e4-8fe9-6b25c465229a.png)

I will pull the regular two plugins in after I update the readme. I will push this plugin out in hopes someone might clean it up or suggest ways to clean it up.

**Comment by lirmont** [comment]
Alright, pull request is out for the raw material and level of detail metrics charts. The 3rd plugin exists in this branch: https://github.com/lirmont/BIMserver/tree/Growth-Chart-Plugins/Charting

Things I think need review/cleanup/BimServer-ification.

__https://github.com/lirmont/BIMserver/blob/Growth-Chart-Plugins/Charting/src/org/bimserver/charting/GrowthByRevisionChartSerializer.java__

_Line 126 of this file:_ Revision ID added as vital part of project info. Reason: it is only vital to this serializer.
_Line 133 of this file:_ Repurposes the download project action. Reason: ignores user because user data is not passed to serializers.
_Line 262 of this file:_ Extensive use of reflection to read fields designed not to be read. Reason: probably a better way to get this information, but reliability is not an issue.

Thanks.
