### ISSUE TITLE
add a new interface

### ISSUE THREAD

**Issue by howlDream** [opensourceBIM/BIMserver#200]
![image](https://cloud.githubusercontent.com/assets/10719871/7151562/b65dc422-e35e-11e4-9f18-ade47e76677e.png)
why the "......Reflector1.java" files don't exsist ?  
Only have the " .class" files ?

And if I want to add a new interface , how can I add a "myinterfaceReflector1.java"  ?

thanks

**Comment by rubendel** [comment]
Would it by any chance be possible to post the _whole_ stacktrace, and not as an image, images are not very search friendly for the people after you having the same problem.

There is no .java file because the Class is being generated (using javassist) only when the interface has changed. The only reason for this is that we don't have to use reflection, which would affect performance negatively. The generated Classes are only a layber between the JsonHandler and the actual implementations though, so you shouldn't have to create those yourself.

If you want to add an interface to BIMserver, have a look at one of the existing interface (like https://github.com/opensourceBIM/BIMserver/blob/master/Shared/src/org/bimserver/shared/interfaces/ServiceInterface.java) and create your own. You might have to add it to the generators somewhere, just search the codebase for ServiceInterface.

**Comment by howlDream** [comment]
Thank you very much for your reply!
