### ISSUE TITLE
error sending password for New User

### ISSUE THREAD

**Issue by SebastianGiovagnoli** [opensourceBIM/BIMserver#309]
I have problems to create new users, it is unable to send the password because an error occurs:
22-02-2016 15:39:27 ERROR org.bimserver.mail.EmailMessage - Error sending email <style>
how can I solve that?

**Comment by rubendel** [comment]
Please post more lines from the log file. Did you configure a SMTP server?

**Comment by oliviersaintgobain** [comment]
Hello,
I configured the smtp server without username and password because my smtp doesn't need it.
The message when I try to reset a password is ok : "A password reset e-mail has been sent".
But, I never receive the mail. Can you please advise ?
I run the final version 1.4.0-FINAL-2015-11-04/bimserver-1.4.0-FINAL-2015-11-04 on Centos/Tomcat.

thanks by advance...
Olivier

**Comment by klacol** [comment]
Hi, we learned, that the authentication at the smtp server is required. We found no possibility to send an email without authentication.  With authentication it workes fine, but you need a smtp server which requires authentication.

**Comment by oliviersaintgobain** [comment]
hi, thanks. I tried to change to my gmail smtp credentials instead of internal smtp server.
- With internal smtp without credentials, message is : mail sent. result is : no mail received.
- With gmail smtp with credentials, message is : sending mail busy. result is : no mail received.
So, maybe my problem is not coming from smtp autentication in the first case ?

**Comment by rubendel** [comment]
Can you state your version of BIMserver? Lately some bugs were fixed in the code that sends emails

**Comment by oliviersaintgobain** [comment]
hello, I checked in the log of my bimserver. I think it's a problem of proxy. I ran bimserver through docker image from jenca/docker-bimserver. everything is ok except this feature.
so, do you how to indicate to Bimserver to use the proxy configuration ?

**Comment by oliviersaintgobain** [comment]
the version I'm testing is the latest release : 1.4.0 FINAL.
I rebuilt the docker image with proxy configuration in Tomcat.
Now, the message in bimserver.log is : 
15-09-2016 12:50:23 ERROR Error sending email <style>
* {
        font-family: 'Lucida Grande', Helvetica, Arial, sans-serif;
}
</style>Dear olivier lapeyre,<br/>

You or someone else has requested your password to be reset, please click the following link to choose a new password: http://10.154.76.75:8080/BIMserver/?page=ResetPassword&username=olivier.orpel@lapeyre.fr&uoid=196610&validationtoken=C0438785732CB66972ACEB35A37532BD&address=http://10.154.76.75:8080/BIMserver<br/>

 334 NTLM supported
 (org.bimserver.mail.EmailMessage.java:86)

thanks again

**Comment by oliviersaintgobain** [comment]
any idea on this message ?
334 NTLM supported
(org.bimserver.mail.EmailMessage.java:86)

**Comment by oliviersaintgobain** [comment]
actually, I'm working in a vm configured in my company network. use a proxy scocket to connect is mandatory.
Anyway, I can use internal smtp server with authentication, but it's working with whanging the emailmessage.java file from the bimserver source code.
I don't use transport.connect(...
I changed the session creation :
Session mailSession = Session.getDefaultInstance(props,
			    new Authenticator() {
	        protected PasswordAuthentication  getPasswordAuthentication() {
	        return new PasswordAuthentication(user, password);
	                }
and just use Transport.send(...

so, this is the solution for me
