### ISSUE TITLE
BIMserver to support CORS

### ISSUE THREAD

**Issue by lijuncheng16** [opensourceBIM/BIMserver#318]
Hi, 
Just wondering does BIMserver service API support the function of CORS(cross origin resource sharing) through tomcat.
To be more specific, I have the following use case:
I want to provide people with a URL link which would point to a specific room view to my deployed bimserver and bimview instance.

Is there any existing facility would allow me to do that or what's your suggestion if I was going to implement that function. Which part (namely, bimview or bimServer) should I mess with.

I have been developing around BIMserver and BIMview for a while and everything works great with my use case. Thanks for everyone's effort so far!

Billy

**Comment by Lawri-van-Buel** [comment]
How would [CORS](https://en.m.wikipedia.org/wiki/Cross-origin_resource_sharing) help? CORS is for requesting stuff from a different domain. For example if I want to use a webfont from Google. Google has to offer the webfont utilizing a CORS header.

So CORS basically is just adding a header to your request. Since from a security standpoint it's a must to run a we service like tomcat behind a reverse proxy, you can just add the required header to the proxy settings.

**Comment by lijuncheng16** [comment]
Yes, I am saying what if other people (a third party site) would want to request a direct view to certain room on bimview. Do I have to provide a CORS header?
BTW, what would you suggest, architecture wise, to implement this function? Should I start with hacking around using just an iframe to access bimview from the external site? or is there any better way of handling this according to your experience?

**Comment by Lawri-van-Buel** [comment]
I would use something like a proxy or other service to do that. 

Or consult with a company that does this kind of thing often. 
(Shameless plug) like https://040lab.com the company I work for has some good experience with these type of webapps.

**Comment by lijuncheng16** [comment]
Thank you very much for your suggestion!

Appreciated!
