### ISSUE TITLE
How to add custom plugins to BIMserver 1.5.x 

### ISSUE THREAD

**Issue by lkmoe** [opensourceBIM/BIMserver#322]
Hi,
I am currently working on a ModelChecker plugin (based on your JavaModelChecker).
In BIMserver 1.4.0 you just had to place the plugin’s .jar file in the /plugins folder which worked fine.
Now I would like to adjust my plugin to work with the BIMserver 1.5.43 Developers release.
I built a .jar file using the latest JavaModelChecker code and placed it in the home/plugins folder where the BIMserver seems to put the .jars of the via BIMviews installed plugins. But it doesn’t seem to recognize my plugin.
Is it not possible to access plugins without using the Repository Server in ServerSettings or might just the way I build my .jar file be wrong?

It would be great to get some help and thanks in advance.

**Comment by rubendel** [comment]
Hi, plugins put in the plugins folder will not automatically be installed, because BIMserver needs to know for which users to install the plugin (and other information). You don't have to use the "Repository Server" setting.

You can call PluginInterface.installPluginBundle to install your own plugins. Those plugins will still have to be on a maven repository, but you could host it yourself if you don't want to use an existing maven repo.

Will create an issue for loading plugins without putting them in a maven repository or loading them from your local Eclipse.

**Comment by lkmoe** [comment]
Ok, I will give it a try. Thanks for your help!

**Comment by rubendel** [comment]
The 1.5.55 release has calls to load plugins from file/url:
```
PluginInterface.installPluginBundleFromFile
PluginInterface.installPluginBundleFromUrl
```

Also the new BIMvie.ws release allows installing plugins via these API calls.

**Comment by whatisor** [comment]
Hi, do you have an official way to deploy new plugin to existing bimserver( system is working, we need to add a new custom plugin)?
