### ISSUE TITLE
Key exists error

### ISSUE THREAD

**Issue by rubendel** [opensourceBIM/BIMserver#334]
This error sometimes occurs in the following situation:
- User tries to checkin a model
- Somewhere in the process the server is stopped
- Server is restarted
- User tries to checkin on the same project
- Object identifiers have already been used, this causes the error

This happens because IFC model data is not stored transactionally anymore, because the "Store" model, which _is_ stored transactionally guards the model-data. A good solution for this would be to cleanup all projects on server-start.

**Comment by Xsoiou** [comment]
Hi Ruben!

I am facing this issue right now on a couple of files. This started when I tried to upload these files on the Bimserver (v1.5.92) but got  java.nio.file.ClosedFileSystemException, so I restarted the server (because I thought it was some kind of bug) and now I get the Key exists error instead. So my question is, what steps should I do when I'm facing this error? Is there any way to get around it without wiping the db?

Thanks in advance.

**Comment by rubendel** [comment]
This has been implemented
