### ISSUE TITLE
How to replace Bimsie1ServiceInterface.download?

### ISSUE THREAD

**Issue by penriister** [opensourceBIM/BIMserver#341]
New BIMserver 1.5 does not have Bimsie1ServiceInterface.download method. Also, no ServiceInterface.download method exists. I have self made BIMserver 1.4 client  which is using Bimsie1ServiceInterface.download for getting the topicId. Then I have constructed URL  for downloading the data in BinaryGeometry format.  What should I do to get my software to work with the BIMserver 1.5?

**Comment by rubendel** [comment]
Most of the old download* callls have been removed because they were very limited in the sense that you could not combine "queries" (for example downloadByTypes only queries on type, and downloadByOids only on ObjectIDs).

The new method you can use is ServiceInterface.downloadByNewJsonQuery. This new JSON based query language is a lot more versatile, but needs documentation and a few improvements. It is however already used in for example BIMvie.ws.

The query that replaces Bimsie1ServiceInterface.download is:
```json
{
	includeAllFields: true
}
```

Other examples of queries can be found by running BIMvie.ws and browsing through the examples in the "Query" tab.

**Comment by penriister** [comment]
I replaced Bimsie1ServiceInterface.download as suggested. How should I then form the download URL?  When using  the BIMserver 1.4 my URL is formed this way: 
serverUrl + "/download?token=" + token + "&serializerOid=" + serId + "&topicId=" + topicId. 
Then I use normal http requests to get the response and it works fine in 1.4 . When my software tries this same with the BIMserver 1.5 and using downloadByNewJsonQuery  to create the topicId, I get "Failed to read past end of the stream" error.

**Comment by rubendel** [comment]
In that case there is probably also an error on the server side, which could help to find out what the problem is.

**Comment by gstslxd** [comment]
Are you using java 3D to visualize a ifc model in the java client? @penriister

**Comment by penriister** [comment]
I am not using Java at all, my client is written with C#.

**Comment by gstslxd** [comment]
Cool！Then your client are based on IfcEngine?

**Comment by penriister** [comment]
My client works  in  the Unity 3d by making WebRequests to the BIMserver API and then visualizing  responses. Currently I can use Collada and BinaryGeometry serialized models.

**Comment by gstslxd** [comment]
Thanks.I will try to use Unity 3d later.

**Comment by willard918** [comment]
Hello, I am trying to do this as well.  Though I am new to the BIM Server, so how would I do this from the beginning?
