### ISSUE TITLE
Connection error 

### ISSUE THREAD

**Issue by rantidev1** [opensourceBIM/BIMserver#362]
While using BIM Server over HTTPS connection , setup page is not getting loaded. 
Check below error from browser console

> jquery-2.1.3.min.js?_v=bimviews-1.3.11:4 Mixed Content: The page at 'https://XYZ/bimserver/' was loaded over HTTPS, but requested an insecure script 'http://XYZ/bimserver/js/bimserverapi.js?_v=bimviews-1.3.11'. This request has been blocked; the content must be served over HTTPS.

Please suggest if there is anything to be done from my end.

**Comment by rubendel** [comment]
You have to change the "Site address" in Server Settings to include httpS. The only trouble at the moment is that you can't access the Server Settings page because of the wrong Site address... So there are 2 ways:
1. Delete database and do setup again, and use the right Site address
2. Do a manual API call, those still work, it's just BIMvie.ws that is not working

**Comment by rantidev1** [comment]
Hi  Ruben ,

a quick question , is it possible to use BIMvie.ws over https or not .
If yes then what should be done to get it working.

**Comment by rubendel** [comment]
Yes, either by executing step 1 or 2 in my previous response...

**Comment by rantidev1** [comment]
Thanks Ruben , BIMvie.ws worked for me over https on my local server, but it didn't work over my company's netwok , seems there is some problem with configuration .
