### ISSUE TITLE
Starting a BIMserver plugin with a BIMserver API call 

### ISSUE THREAD

**Issue by GreenUtil** [opensourceBIM/BIMserver#406]
Hello, 

We would like to start a BIMserver plugin, for example the clashdetection internal service, with a BIMserver API call for a specific project/subproject. 
At the moment it seems that a plugin can only be started from the BIMvie.ws client as an Action on a certain revision.
We (http://www.3dgeosolutions.nl) are making a platform for the building industry. In this platform we are using BIMserver, BIMSurfer and clashdetection. Because we are making our own client userinterface we'd like to start clash detection with a BIMserver API call.
We hope more people are interested in this feature, so we can build it together.
Leon van Berlo has my contact information, email and phone number and so on.
Don't hesitate to contact me ! :-)

Greetings,

Barent Brouwers

http://www.3dgeosolutions.nl

**Comment by rubendel** [comment]
All functions that are available in BIMvie.ws are available in the BIMserver API, because that's just what BIMvie.ws uses. Open your JavaScript console (networking), perform the action you are interested in, view the original JSON request and you known which method to call.

In this case the method is ```ServiceInterface.triggerNewRevision```
