### ISSUE TITLE
Using Query Engine plugins

### ISSUE THREAD

**Issue by carloslubbers** [opensourceBIM/BIMserver#418]
Hi,

I would like to query my IFC model using the Query Engine plugins. The API specifies a lot of methods to enable/find the installed Query Engines, but no way to use them? The download calls don't have a parameter to specify the query engine, it defaults to the json queries. The BIMvie.ws query panel allows me to select an engine but the download function isn't working, which makes me think that this used to be a working feature.

**Comment by rubendel** [comment]
I'll use this issue to describe the current state of querying in BIMserver.

**Querying in BIMserver < 1.5**
In versions before 1.5 there was the ability to write query plugins for BIMserver. Only 2 implementations ever existed; "JavaQueryPlugin" and "BimQL".

The first one basically allowed one to write Java code to query a model (the code would be compiled at runtime by the plugin). Being Java (a turing complete language) everything was possible, but you had to learn/known Java.

BimQL had it's own text-based syntax which was a bit more limited in my opinion.

The only way a query engine would work was by loading the complete model from the database into memory, and then selecting what data te return from that. This did not scale to reallife models on laptop computers.

**Other methods in BIMserver < 1.5**
Along the query engines described above, there were also numerous download* calls (downloadByTypes, downloadByGuids etc...). These calls were very limiting because no combinations of queries could be made.

**Querying in BIMserver 1.5**
All the download* methods have been removed and replaced by one method called "download". This method has a "query" argument which contains a query serialized as JSON. Please note that when using the BIMserver interface via JSON you'll have json-in-json and need proper escaping.

This new JSON query language does not need to load the whole model into memory and is a lot faster. It also gives more ways of querying than before, but should be easier for non-programmers. It is still however a low-level kinda query language which hopefully will be used by higher-level languages (such as maybe a V2 of BimQL).

The language is also in development (at least as long as 1.5 has not been released).

**Query engines in 1.5**
I think we don't need them anymore, but not everybody agrees so that's why they are still there, but they probably don't work because nobody is maintaining this. Hope this clarifies the current state a bit.

**Comment by carloslubbers** [comment]
Thanks for the detailed explanation. I would like to try using the JSON queries, but the only available documentation on this are a few examples in BIMvie.ws. If the JSON queries are very powerful, would it be possible to maintain some kind of documentation about this format (which can change over time, since its in development)?

**Comment by rubendel** [comment]
Documentation has started, but it's not complete: https://github.com/opensourceBIM/BIMserver/wiki/JSON-Queries
