### ISSUE TITLE
Version issue about using local build plugins

### ISSUE THREAD

**Issue by agdsdl** [opensourceBIM/BIMserver#465]
We want to make some changes to plugins(bimviews, bimsurfer,bimserverapi...), and build them locally instead of downloading from maven repo.

I use the latest release of "bimviews" which version is "0.0.71". By looking at the "pom.xml", I found it depends on "bimsurfer" with vserion "0.0.3" of which the release tag is updated one year ago.

Also the latest release of "Console" with version "0.0.4" depends on "bimserverapi" with version "0.0.83" which is updated one year before.

And the "plugin.xml" of bimserverapi with tag `bimserverapi-0.0.83` have missing a `<name>` field, which will cause a runtime error. 

Question is, is it correct to use so old plugin versions?
What's the correct plugin versions of the latest bimserver release?

**Comment by rubendel** [comment]
At the moment the versioning system does not work optimally, we are not sure yet how to get it sorted.

A few notes:
- The javascripts/html/css projects like BIMvie.ws/BIMsurfer/JavaScriptApi/Console do have pom.xml files, but the versions in the dependencies are not used, that's why those versions in there are outdated, I'll remove them if possible
- The latest version of the JavaScriptApi project does have a name in the plugin.xml, we can't change releases
- Usually when you use the latest released version of BIMserver (draft), you should use the latest versions of all plugins as well. That is the only configuration we try to test, all other configurations might work, but there are just too many to test them all.

**Comment by agdsdl** [comment]
Got it! Thanks!
