### ISSUE TITLE
Download of a model in binarygeometry  fails

### ISSUE THREAD

**Issue by penriister** [opensourceBIM/BIMserver#469]
I am using  latest version of the BIMserver.  3d view of  the model works with Bimviews, but when I try to download the model using binarygeometry serializer, the  resulting file is empty.  Does 3D viewer of bimviews request the data serialized with binary geometry?
The BIMserver info shows that it is  starts caching, renames the temp file, and has done caching. No error messages shown. 

Regards,
Pentti Riikonen

**Comment by rubendel** [comment]
There are two "stages". The first stage will download a JSON representation of the model for the internal javascript object model. This first stage is what you see is being cached.

The second stage is implemented via WebSockets, but before it was using a binary serializer (probably the one you are trying to use). So because it's not used anymore, chances are that it doesn't work anymore. Maybe you you can use the websockets version in your situation?

**Comment by penriister** [comment]
I have some experience about WebSockets, but not with the BIMserver.  What kind of requests and responses the WebSocket connection with the BIMserver  expects?  Are there some documentation about the WebSocket connection with the BIMserver. 
Regards,
Pentti Riikonen

**Comment by rubendel** [comment]
No documentation, but you can have a look at the code of the BIMsurfer project.
