### ISSUE TITLE
Does bimserver run slowing when do the continued checkin jobs?

### ISSUE THREAD

**Issue by yanzhenxing** [opensourceBIM/BIMserver#482]
Hi, Ruben,

I run the bimserver in version 1.5.68-SNAPSHOT. And I find the bimserver will be slowing when I continued check in the ifc files. 
For example, I upload a 500M ifc file and it takes 13 minutes at first time, but 20 minutes at second time, 40 minutes time , and so on .It will be more and more slower.
I wonder that which factors influence the performance?

**Comment by berlotti** [comment]
Could you please provide log files and possible the original IFC files?

**Comment by btc100w** [comment]
[bimserver.log](https://github.com/opensourceBIM/BIMserver/files/2083173/bimserver.log)

Hi,Berlotti
    I have encounter the same problem,when I check in more and more ifc files in different projects,my computer becoming more and more slower
    I want to know what's the reason,is the browser still keep the previous memory when I check in another or other reasons ? and how to change it if  I want to run it normally after i check in many files?

 I have uploaded my log file. Looking forawrd to your reply,thank you

**Comment by rubendel** [comment]
Which version of BIMserver?

**Comment by berlotti** [comment]
Logfile says 1.5.101

**Comment by rubendel** [comment]
Ok. Not sure what the browser has to do with this. I see 3 files uploaded, can't image that slowing BIMserver down. How much memory has been assigned to the BIMserver VM?

**Comment by btc100w** [comment]
I use the default "Max Heap Size" 4096M and Stack Size 1024K.As I am testing on my local windows environment,I check the windows task manager,the memory about chrome is increasing sigfinicantly when i checkin more and more files , and more slower because of the lack of mamory available.

The four screenshot is the process from 1.checkin nothing->2.check in 1 file->check in 2 file ->check in 3 file -> refresh the browser

when I check in 3 file,my computer is too slow to use,it's seem like somthing ablout memory leak ? I want to solve the problem, For example,When I checkin another file,the previous file memory can be recovery.so I need some help and advice.Thank you.


![0](https://user-images.githubusercontent.com/40053275/41156832-246cab2c-6b56-11e8-96b1-60d868ee301d.png)
![1](https://user-images.githubusercontent.com/40053275/41156841-2e7f606e-6b56-11e8-8ba5-2771f4d6e849.png)
![2](https://user-images.githubusercontent.com/40053275/41156849-338a62b6-6b56-11e8-80c0-455f16eeeae4.png)
![3](https://user-images.githubusercontent.com/40053275/41156861-3d339eae-6b56-11e8-9793-8efac146d21a.png)
![4](https://user-images.githubusercontent.com/40053275/41156928-7afca65e-6b56-11e8-8959-42363e44c960.png)

**Comment by rubendel** [comment]
Not a BIMserver issue, closing
