### ISSUE TITLE
Local plugins disapear after reboot

### ISSUE THREAD

**Issue by Jpjob314** [opensourceBIM/BIMserver#494]
Hi Ruben,

I noticed that when you install a plugin (or web module) using local jar from the bimvie.ws interface, the plugin disapear after server reboot. 
I supposed it was coming from my build so I tried with some plugins tooked from the /plugin folder but the same result apeared.

- Installed date is empty in the **Installed Plugin Bundles** section
- Plugin works correctly until you reboot
- Jar still exists in the plugin folder

To get the plugin back, I have to delete the jar from the folder and push it again from the interface.

Any inputs ? 
Thank you

**Comment by rubendel** [comment]
Thanks for the clear description of the problem. It has now been fixed in GIT master. From now on there is a distinction between LOCAL plugins (installed via JAR file, like in this example), and LOCAL_DEV (installed by a -plugins argument in your IDE (Eclipse)). The latter ones are automatically loaded, and now the LOCAL plugins are too.

**Comment by Jpjob314** [comment]
Thank you !
