### ISSUE TITLE
No webmodule bimserverjavascriptapi found

### ISSUE THREAD

**Issue by tornado96** [opensourceBIM/BIMserver#504]
@rubendel,hello
I have just installed the version of bimserver 1.5.69.
during the setup page, I install plugins by upload jar locally, and it succeed and can load the bimviews page.
But when I restart the server, and click the bimviews link on the home page, it cannot load the bimviews but show "No webmodule bimserverjavascriptapi found" only.
did I miss something?
thanks!

**Comment by webdada** [comment]
@tornado96 @rubendel 

I actually just had the same issue, so instead of creating a new issue I am commenting on this issue - I have installed bimserver 1.5.69, using the new upload local jar file capability.  The installation worked, even thought we need to be careful on which jar file to choose (there is one that we should not choose). Now I am back to the server a few weeks later, the server was restarted by network team, so I am just restarting the BIMServer, now I can not go into BIMViews or the API screens. 

http://<server>:8080/apps/bimviews/
No webmodule bimviews found 

I also check the home/ plugin folder, all plugins seem to be there, including BIMViews
 E:\bim-tools\home\plugins\org.opensourcebim.bimviews-0.0.78.jar

It seems that after restarting BIMServer - it may not recognize the installed modules anymore.

Regards,
Sam

**Comment by rubendel** [comment]
I could only reproduce this when I deleted webmodule plugins and then installed them again. Could not reproduce as described.

https://github.com/opensourceBIM/BIMserver/commit/a3970103e8548173eddaf68a5757a01d5afe6628
