### ISSUE TITLE
Queries do not seem to work properly

### ISSUE THREAD

**Issue by stestaub** [opensourceBIM/BIMserver#526]
How can I download all geometries via the GeometryMessagingSerializer without having to add an explicit list of oids?

In a previous version I used the following json query:
```
{"type":"IfcProduct","includeAllSubtypes":true,"include":{"type":"IfcProduct","field":"geometry","include":{"type":"GeometryInfo","field":"data"}}
```

But this query used with any of the GeometryMessegingSerializers only returns the start message but no Geometries.

Also the Query examples in bimvie.ws do only return an empty object list with any Serializer....

I see that the bimsurfer uses a different query that includes a list of oids to download. That still seems to work but its not that convinient to allways provide all oids if you just want all geometries.

I also tried with installing the BimQL plugin but it did not change anything.

**Comment by rubendel** [comment]
The query language has slightly changed to make it more consistent, I'll update the BIMvie.ws examples today.

**Comment by rubendel** [comment]
Updated the test queries in BIMvie.ws (git), will be in the next BIMvie.ws release.

Basically what has changed is that when you want to include all subtypes, you have to make the query part an object. This way we can be more flexible when querying for multiple types (you can decide for every type whether subtypes should be included).

Also the "includeAllSubtypes" has now changed to "includeAllSubTypes", note the capital "T". This was not intentional, but changing it back will (again) lead to a lot of issues on github from people using incompatible versions...

Old:
```
{
  "type": "IfcProduct",
  "includeAllSubtypes": true
}
```

New:
```
{
  "type": {
    "name": "IfcProduct",
    "includeAllSubTypes": true
  }
}
```

**Comment by stestaub** [comment]
Tank you, with this it works.
