### ISSUE TITLE
Uploading doesn't always report error message to user

### ISSUE THREAD

**Issue by ysangkok** [opensourceBIM/BIMserver#556]
When uploading the file at https://hushfile.it/592c22c69af2a#AwrpRI2O3ecDuAmP_pIjNmCAV3BWvwr30tfrazqJ from a local file to bimvie.ws, I get a Bootstrap danger div saying "null". On uploading https://hushfile.it/592c23eb7c862#JJIITFuZZ8g7ImLRm783M7TswsfAVP_3_ZzgH9_Q I get "Value buffer sizes do not match for IfcCartesianPointList3D 1451/509", so I was expecting a more elaborate error message.

**Comment by rubendel** [comment]
The file seems to be invalid. I am working on a better error message.

Where I think the file is invalid (but the IFC spec is kind of vague about this):

```
#197= IFCTRIANGULATEDFACESET...
```

The second argument in that entity should be $ or a reference to another entity. In this file a multidimensional array is embedded, which I don't think is valid here. Especially because the referenced "IfcDirectionList" type has inverses, which cannot be used when embedding the thing.

**Comment by ysangkok** [comment]
The file was generated by Archicad, so unfortunately I can't change this. Not implying that you said I could, of course. :)

**Comment by rubendel** [comment]
Hmm I think I was looking at the wrong version of the documentation (RC3), this can actually be embedded, I'll come back to you about this.

**Comment by rubendel** [comment]
Took a while, but this is now fixed in git master head.
