### ISSUE TITLE
Checkin time too long

### ISSUE THREAD

**Issue by xie-qianyue** [opensourceBIM/BIMserver#570]
I spent 15 hours to checkin this [file](https://www.dropbox.com/s/rbukt8wv4u5oh7w/1251522948326460-98-%E9%AB%98%E6%96%B0%E6%96%87%E5%8C%96%E4%B8%AD%E5%BF%83%E6%B4%BB%E5%8A%9B%E7%8E%AFA%E5%8C%BA.ifc?dl=0), which is not so big, about 173 Mb.

The vm option is setting -Xmx4g. The CPU is i5-6500 3.2GHz. Can you have a look at this file and see whether it's normal that it takes so long to checkin?

The version of bimserver is 1.5.74.

**Comment by rubendel** [comment]
It all depends on the content of the file, filesize does not say anything. I think 4GB could be a problem though, if the VM is constantly using max memory, it will spend a lot of time garbage collecting.

I can think of 2 other possibilities:
- There is very complex geometry in the file, IfcOpenShell has a hard time processing it (you can verify this by checking in the file again and have a look at your OS its processes, if IfcOpenShell (GeomstryServer) uses 100% CPU all the time then that's it. We can't do much about that except hope for a faster version if ifcOpenShell
- Concurrent modifications. Those could be happening if other stuff is going on in BIMserver at the same time. For example logging in with the same user during checkin will cause the checkin process to restart, although this specific case has been fixed with an option in the new version.

**Comment by xie-qianyue** [comment]
Thanks for the explaination. It should be the first reason that you mentioned. On the server we have 32 or 64GB memory, may it have better performance.

If it's the garbage collecting that spends most of the time, could I tune the JVM parameters to make it faster?

**Comment by rubendel** [comment]
Well yeah give it more memory. That's what the -Xmx option is for. If your machine is not running any other significant applications, you only need a few gigabytes for the OS, the rest you can give to BIMserver.
