### ISSUE TITLE
Implementing BIMserver Backup and Recovery Strategy

### ISSUE THREAD

**Issue by stegh** [opensourceBIM/BIMserver#622]
Hello, 

didn't find much about this topic, therefore I'm going to write a ticket ;)

I'd like to implement some kind of "BIMserver Backup and Recovery Strategy".

Do you have any hints, concepts, ideas?

What to Back Up? (Determine how much data you need to backup)
(Do you just copy the file system data? 
 Do you need to stop BIMserver / Apache Tomcat for backup?
 etc.)

Testing backup and recovery strategy?
(Is it easy to restore and get BIMserver up and running with existing data?
How quickly can you recover your BIMserver in the event of a disaster?
How do you setup on new server, use existing backup?
etc.)

Thanks in advance!
Regards,
 Thomas

**Comment by rubendel** [comment]
You can just copy the data in the home folder, best to stop your BIMserver. To restore, just move the copied data back and start BIMserver.

**Comment by malinkody** [comment]
I understand that this kind of recovery & backup strategy will work within the same version of a BIMServer. But is it possible to migrate the data of one Server to another? Also if we update the BIMServer can we keep the old data? Is the BIMServer safe to upgrade? As it is, it is really hard to recommend this for any kind of production use.

**Comment by xie-qianyue** [comment]
I would also like to know whether we can keep/migrate the data when the BIMServer version upgrades, especially when the schema version upgrades.

**Comment by rubendel** [comment]
It depends. After a production version is released (for example 1.5), we use database-upgrade scripts when doing schema changes (for example from 1.5.90 to 1.5.91). These scripts are able to upgrade an existing database to the new schema. So as soon as 1.5 is released, you'll be able to upgrade it for at least a year.

Sometimes we do changes that cannot be reflected with the upgrade-scripts. In those cases you cannot upgrade your database and the only option is to migrate the data via the API calls (some people have successfully upgrade 1.3 to 1.4 for example using this method). This usually happens when we move a minor version, for example from 1.5 to 1.6 (happens every few years).

Of course you should always backup your data before doing a software upgrade, even if it is supported, just like you would with any other production system.

**BDB**
The actual storage format (BDB) is always upgrade-able, for every new version we use, they use their own versioning system within the database, and it is also operating-system independent. You can move the data from a Windows machine to a Linux machine with no problems.

**Comment by xie-qianyue** [comment]
Thanks for the suggestions of minor / patch updates!
