### ISSUE TITLE
detailed steps of using BIMserver and BIMsurfer?

### ISSUE THREAD

**Issue by cnyzgkn** [opensourceBIM/BIMserver#634]
I want to use BIMsurfer to connect to BIMserver but have no idea.  Could you help me on detailed steps of using BIMserver and BIMsurfer?

Now I downloaded bimserverjar-1.5.88.jar and get BIMserver running in my local machine as below:
![01](https://user-images.githubusercontent.com/5706598/31897630-8b3bb886-b849-11e7-92d0-426fbf5fdd8b.jpg)

Then I configured it so when I access http://localhost:8082/ I got this page:

![01](https://user-images.githubusercontent.com/5706598/31897708-cfab2894-b849-11e7-8122-d161aad767f9.jpg)

So what shall I do next?

Does it mean BIMserver run successfully?

I synced BIMSurfer into my local machine, how can I use BIMSurfer to connect to BIMServer? Open BIMsurfer\index.html failed.

Above all, is there a detailed list of download/install/configure/demo of using BIMsufger to connect BIMServer and open/view ifc files?

Thank you

**Comment by garywangcn** [comment]
Looks like no plugin is installed, please refer to below link to install them:
https://github.com/opensourceBIM/BIMserver/wiki/Installing-without-internet-connection

After it completes, you will see below steps:

![image](https://user-images.githubusercontent.com/22828078/31927343-3e1e3984-b8c6-11e7-9f49-e40a0388db6d.png)

And then click bimviews highlighted in above image.

**Comment by cnyzgkn** [comment]
@garywangcn  Thanks a lot for your help.
I have access to internet. Why it shows "No internet connection"?

**Comment by rubendel** [comment]
Do you use a proxy server to access the internet? That usually happens in corporate networks.

**Comment by cnyzgkn** [comment]
@garywangcn no I didn't use any proxy server.
1. I found this page: https://github.com/opensourceBIM/BIMserver/wiki/Outgoing-internet-connection
which said I should have access to http://central.maven.org/maven2 to update the plugins, but I can't open http://central.maven.org/maven2. 
Can you open it?

2. I switched to download plugin .jar files and install them offline as below:

![image](https://user-images.githubusercontent.com/5706598/31934459-be521702-b8de-11e7-91d7-9b65c04b5a21.png)


Then try to setup them offline and succeed:
![image](https://user-images.githubusercontent.com/5706598/31934528-eb26e15e-b8de-11e7-897a-767bce2d6001.png)

But after refesh I found there is NO bimViews installed at all:
![image](https://user-images.githubusercontent.com/5706598/31934683-64c334d6-b8df-11e7-8611-6b34c5a64288.png)

So what is the problem?

**Comment by cnyzgkn** [comment]
@garywangcn  I got the reason. It's because I downloaded the wrong version. Thank you~

**Comment by cnyzgkn** [comment]
@garywangcn 
I am able to open bimviews: http://localhost:8082/apps/bimviews/
![image](https://user-images.githubusercontent.com/5706598/31951907-df53736e-b911-11e7-953e-5b5cee2b51b3.png)

but open bimsurfer http://localhost:8082/apps/bimsurfer/ fails:
![image](https://user-images.githubusercontent.com/5706598/31952106-63a54016-b912-11e7-83fd-6c170b8d203b.png)


Why? 

How can I connect bimsurfer to bimserver and open a ifc file?

Or shall I edit BIMsurfer\docs\example_BIMServer.html?

**Comment by garywangcn** [comment]
@cnyzgkn I'm also encountering the problem about bimsurfer, don't get the root cause yet.

**Comment by rubendel** [comment]
Is it installed, are there any errors in the server log?

**Comment by gnarale** [comment]
@rubendel I am having same issue. After successfully installing bimserver, I installed all plugins including bimsurfer, bimviews etc. I can see jar files for these plugins under home/plugins. When I open localhost:8082 and click on bimsurfer, I get 404 page. But when I click on bimviews, I am able to open projects, view 3d files etc. What am I missing in terms of loading bimsurfer so that I can view ifc files using bimsurfer?

**Comment by mohanasaraf** [comment]
Hey @gnarale and @cnyzgkn any update on this. Were you able to get bimsurfer running ?

**Comment by RyanHow** [comment]
BIMViews is using BIMSurfer under the hood. So for an out of the box experience, use that. To use BIMSurfer directly, you'll need to do a bit of coding. As far as I can tell anyway.

**Comment by rubendel** [comment]
@RyanHow  Correct, BIMsurfer is a reusable component, no standalone application. In the future I'll remove it from the web modules page to make this less confusing.

**Comment by xierunhua** [comment]
@rubendel  I think people just watched this video to use bimsurfer. 
https://www.youtube.com/watch?v=ndXakWs63dY

**Comment by rubendel** [comment]
Wow that's a 6 year old video

**Comment by xierunhua** [comment]
still cool.
so how to develop the bimsurfer?
I clone the project https://github.com/opensourceBIM/BIMsurfer into Eclipse. But don not know to use it . Any suggestion?

**Comment by GravTrainee** [comment]
This would be nice to know, how do I start developing UI for bimsurfer?

**Comment by Mit-hf** [comment]
![image](https://user-images.githubusercontent.com/46521167/94235419-1b579000-ff3e-11ea-939a-9475c5f6e32c.png)

**Comment by Mit-hf** [comment]
![微信图片_20200925144854](https://user-images.githubusercontent.com/46521167/94235502-43df8a00-ff3e-11ea-923a-b1c0d9bdbc43.png)

**Comment by Mit-hf** [comment]
What is the reason for the unsuccessful installation? I am downloading the corresponding version of the offline plug-in, looking forward to your reply!

**Comment by hlg** [comment]
This particular plugin has additional dependencies which are resolved via Maven, downloaded and installed from the remote Maven repository. Thus offline installation it is not possible at the moment. We should add some information about this to the documentation.

It may be possible to install the dependencies to your local Maven repository in advance and then later use the local repo for offline installation. I say this with a bit of caution because I am not sure that the dependency resolution falls back to the local repo in all cases.

**Comment by Mit-hf** [comment]
Thank you for your suggestion. Do you have any documents for bimserver? The document explanation on the official website is very one-sided.thank you！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hlg"<notifications@github.com&gt;; 
发送时间: 2020年9月25日(星期五) 晚上6:26
收件人: "opensourceBIM/BIMserver"<BIMserver@noreply.github.com&gt;; 
抄送: "568530599"<568530599@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [opensourceBIM/BIMserver] detailed steps of using BIMserver and BIMsurfer? (#634)





 
This particular plugin has additional dependencies which are resolved via Maven, downloaded and installed from the remote Maven repository. Thus offline installation it is not possible at the moment. We should add some information about this to the documentation.
 
It may be possible to install the dependencies to your local Maven repository in advance and then later use the local repo for offline installation. I say this with a bit of caution because I am not sure that the dependency resolution falls back to the local repo in all cases.
