### ISSUE TITLE
Color issue when Check In as stream

### ISSUE THREAD

**Issue by PatriceMoreau56** [opensourceBIM/BIMserver#668]
Hi,

Thanks for your good work on the BIMserver. I have an issue with the colors of my building example.
[Chanteloup.zip](https://github.com/opensourceBIM/BIMserver/files/1538720/Chanteloup.zip)

When I check in an ifc file with Ifc2x3tc1 (Streaming) deserializer, the second floor of my example appears with brown color 
![chanteloup ci streaming](https://user-images.githubusercontent.com/34338280/33711008-b7e2a68a-db42-11e7-9d9b-3a4556331d45.png)

When I check in the same file with Ifc2x3tc1 deserializer (without streaming), the second floor appears white as it has to be 
![chanteloup ci file](https://user-images.githubusercontent.com/34338280/33711068-de9ea1ac-db42-11e7-8f5c-d324091f7726.png)

When I download the file as an IFC (check out operation), the color is OK whatever serializer plugin I use (streaming or not).

As far as I understand the BIMviews, it uses the BIMsurfer for the 3D. Do you think the issue come from the BIMsurfer?

Bimserver 1.5.92 settings:
Bimserverapi : 0.0.122
Bimviews : 0.0.90
Bimsurfer : 0.0.43
IfcPlugins : 0.0.33
IfcOpenshellPlugins : 0.5.25
BinarySerializers : 0.0.27

**Comment by rubendel** [comment]
Thanks for the model! This has now been fixed in GIT HEAD.

Background info: The upper-storey walls were different from the other walls in that they used recursive boolean operations to define the geometry (which is perfectly fine). In that case, the queries BIMserver uses to determine which info to include in the IFC files sent to IfcOpenShell omitted the style information, so they fell back to a default color.
