### ISSUE TITLE
Data From the Json api and BinaryGeometry is not se same

### ISSUE THREAD

**Issue by meyerf93** [opensourceBIM/BIMserver#708]
Hi,

I try to get information by JSON API and the binarySerializer to recreate the geometry on Unitry 3D.
The problem is that the data from JSON api and the binarySerializer is not the same.

Did you have any documentation to explain the both way to get data ?

**Comment by rubendel** [comment]
The JSON API can be used to call methods on BIMserver. Most of the calls are documented in the code (or you can use the Console app).

The BinarySerializer serializes triangulated geometry of queried objects. So yes they don't give back the same data.

The code should be pretty self explanatory. For most projects you'd probably want to write your own serializer because the BinarySerializer is basically written specifically for the JavaClient and BIMsurfer.

**Comment by rubendel** [comment]
All the information available in the IFC file is available through the different API's and plugins. You can for example download a subset of the model (of the whole model) via the JSON serializer if that's easier to parse than IFC-STEP.
