### ISSUE TITLE
Tomcat restart fails to stop threads

### ISSUE THREAD

**Issue by stestaub** [opensourceBIM/BIMserver#710]
When I try to restart the bimserver on my Ubuntu server, there seems to be an issue with some threads that can't be stopped:

```
The web application [ROOT] appears to have started a thread named [EMF Reference Cleaner] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
 org.eclipse.emf.common.util.CommonUtil$1ReferenceClearingQueuePollingThread.run(CommonUtil.java:70)
```

And 

```
The web application [ROOT] appears to have started a thread named [UniqueName0.8586790344946474_Worker-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
```

As the log states, this could lead to Memmory leaks  I wonder what the cause could be that those threads can't be stopped, and how we could solve it.

The background on this is, that after some period of running the bimserver, it starts to fail on requests which previousley worked. Restarting the bimserver seemed to fix that problem, thats where I stumbled upon those Log entries...

I wonder if those two problems are related or if its just coincidence.

Any help or input appreciated.

**Comment by plamentotev** [comment]
To me it looks like that Tomcat tries to gracefully stop the bim server application but there are some threads that continue to work for some reason[1]. Will that lead to memory leaks? It depends on how you restart the application. If you only restart the web app (and not the Tomcat) then as the logs says "is very likely to create a memory leak". That is because Tomcat will start a new instance while not all resources from the old one are reclaimed. But if you restart the whole Tomcat then the OS will make sure that all resources used (especially memory and threads) by the old Tomcat process are reclaimed. Even if the process (Tomcat) itself failed to free them properly. And word of advice - sometimes Tomcat has this nasty habit to not stop when you ask it to do so - when you restart it make sure the old process is terminated and if not, kill it.

>The background on this is, that after some period of running the bimserver, it starts to fail on requests which previousley worked. Restarting the bimserver seemed to fix that problem, thats where I stumbled upon those Log entries...
>
>I wonder if those two problems are related or if its just coincidence.

I don't thinks so (although of course it is possible). Do you get any errors(or any unusual messages) in the logs when the requests start to fail? That would help to find the issue.

[1] I haven't dug much into the issue yet, but those threads are from external libraries. So it's either problem in them or bim server does not properly  shutdown them.

**Comment by rubendel** [comment]
BIMserver probably does not shut them down correctly. I'll have a look at that later, but it's not high on the priority list. My experience with running in application containers is that you'll always have problems like this and it's best to (like @plamentotev said) restart the whole tomcat application. That will get rid of everything for sure.

We have a few BIMservers running continuously for months (and doing something) and not seen the problem with requests not coming through. Parts of the logfile would be useful to find out what's causing that.

**Comment by rubendel** [comment]
Just had another look at this. 

**Quartz**
This is actually stopped during BIMserver shutdown (`BimServer.stop()`). Unless exceptions are thrown or it takes a long time to shutdown, I don't see why this one should keep running (it's not here). Further feedback is appreciated if this is still a problem.

**EMF Reference Cleaner**
The "EMF Reference Cleaner" should automatically stop on JVM shutdown since it's a daemon thread. However tomcat redeployment is not a JVM shutdown so that's why it kept running. I just disabled this entirely since I don't see why we need it, also there seems to be no way to kill it's thread (this I would say is an EMF bug).
