### ISSUE TITLE
Checkout not working as expected

### ISSUE THREAD

**Issue by nyrhilak** [opensourceBIM/BIMserver#736]
I have been making nodejs program which needs to checkin and checkout files. When I try to checkout, I get an error message

> { response:
>    { exception:
>       { __type: 'UserException',
>         message: 'Only IFC or IFCXML allowed when checking out' } } }

Even when I use the following function

```
var query = JSON.stringify({includeAllFields : true}).toString("base64");
return new Promise((resolve, reject) => {
    var Opts = {
    uri : 'http://localhost:8082/json',
    method : 'POST',
    json : 
          {
           "token": logToken,
           "request": {
           "interface": "ServiceInterface", 
           "method": "download", 
           "parameters": {
               "roids": [roid], //Gained by calling getallrevisionsofProject
               "query": query,
//Taken from getAllSerializerForRoids->response[i].oid, I have tried all IFC2x3tc1 serializers 
//and IFC4 serializers
                "serializerOid": serializerOid, 
                 "sync": "true"
             }
             }
           }
        }
        request.post(Opts, function(error, response, body){
            if(error) reject(error);
            resolve(body.response);
        })
    })
```

**Comment by rubendel** [comment]
I don't think the checkout functionality is used much anymore. Just to be sure, do you want to "lock" the specified revision (which is what checkout does), or do you just want to download the revision? Because in that case, you can simply use "download" for that purpose.

Ob course any calls available should be working, I'll have a look and see why "checkout" is not working as expected.

**Comment by nyrhilak** [comment]
I got this working with download, but just thought that available calls should work. Thanks for your time
