### ISSUE TITLE
Geometry slower to load since version 1.5.92

### ISSUE THREAD

**Issue by bastienmenis** [opensourceBIM/BIMserver#741]
I have upgraded from version 1.5.88 to 1.5.100 and noticed that the models were significantly slower to load than before. This affects BIMvie.ws (bundled with BIMserver) and BIMsurfer (latest)

I tested every released version since 1.5.88, this issue started occurring with version 1.5.92 (1.5.90 is ok).

Here are some stats, for loading the same IFC2x3 model on versions 1.5.90 and 1.5.92, using BIMvie.ws as client in both cases. The number of primitives loaded is the figure logged in the browser console.
* v 1.5.92: Loading time 18s; data transmitted over websocket: 17.3MB; number of primitives loaded in BIMvie.ws: 951,410
* v 1.5.90: Loading time 4s; data transmitted over websocket: 3.6MB; number of primitives loaded in BIMvie.ws: 163,616

It does appear that when multiple objects are using the same geometry, the same binary geometry is sent multiple times.

**Comment by rubendel** [comment]
This probably has to do with an optimization that was on by default in earlier releases, but now off by default. You can enable this optimization again in the Server Settings (Optimize mapped items). It does however produce problems in certain models, that's why it's now disabled by default. This feature can be implemented without errors when certain changes have been done in IfcOpenShell, but the timeline for that is unknown.

**Comment by rubendel** [comment]
Just an update, I am working on fixing this problem, hoping to enable this feature by default in new releases.

**Comment by bastienmenis** [comment]
Great, thanks!

**Comment by rubendel** [comment]
Cleaning up old issues, this has been fixed and the feature is now on by default and extensively tested.
