### ISSUE TITLE
Local plugins loaded slowly in dev mode

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#777]
When I run BIMserver via the LocalDevBimServerStarter, plugins from local directories are only appearing in the list of installed plugins and other places after a considerable amount of time. Trying to execute their functionality, e.g. trigger a service, before they are loaded, naturally results in errors. Why is that taking so long? Does BIMserver carry out some other background task before loading the plugins? I did not check whether it is the same with running from the normal Jar. This might be acceptable for normal server operation, but is a bit inconvenient for plugin development.

**Comment by rubendel** [comment]
Hi Helga, at some point, BIMserver did some cleanup of the database during startup, which was implemented badly and took longer for bigger databases, this has been fixed in GIT, but I have yet to make a new build. But I assume you are running from GIT master?

Other than that I can't actually replicate this, but that might be my hardware too. Are you running from SSD? Any anti virus software installed? How long would you say it takes before everything is working?

I could look into at least making sure the "RUNNING" status becomes active when everything (for example also the web modules) are ready for use.

> Just a tip in case you are not familiar with it, when you run a Java program in Debug mode (in Eclipse), a lot of small code changes can be hot-code-replaced, so there is no need to restart the server.

**Comment by hlg** [comment]
Git head of master: yes, SSD: yes, AntiVirus: yes. Currently it takes roughly 10s until server state is RUNNING, another 10s until bimvie.ws is loaded and then 20-30s until the local plugin shows up, the remote plugins are there earlier. I think yesterday it was longer, but did not measure. I see, there may be plenty of reasons.

Not sure when the status should be considered "RUNNING". If you want to leave it as it is, you can close this issue.

Thank your for the debugging tip. I am using IntelliJ, but hot-swap works there too, just tried successfully.

**Comment by rubendel** [comment]
Added this to the next major release milestore. As soon as BIMserver goes to "RUNNING" mode, all plugins should be in working order including the web modules.

**Comment by rubendel** [comment]
I have added a few more lines of logging, so you can see what's going on. I have kept the state "RUNNING" the way it is because in a sense BIMserver is RUNNING and changing this has too much impact on the rest. Disabling antivirus crap certainly would help (making anything faster)
