### ISSUE TITLE
getting geometrical data of objects with Javascript API

### ISSUE THREAD

**Issue by orashkenazi** [opensourceBIM/BIMserver#780]
is there a way of getting the geometrical data (mainly i need the vetices ATM..) using the JS API?

I get the geometryInfo using"getGeometryInfo" of  "ServiceInterface", though i find only min/max bounds, and I don't manage to find any other relevent data.

is this accessible at all using the js api?

thanks,
Or

**Comment by rubendel** [comment]
Performance-wise it does not make sense to write this type of info to JSON. For that specific reason (and because JSON cannot be streamed, at least not by the "native" JSON.parse method) there is a binary serializer plugin you can install for BIMserver.

To see how this works, have a look at the BIMsurfer code base, for example https://github.com/opensourceBIM/BIMsurfer/blob/master/bimsurfer/src/BimServerGeometryLoader.js
