### ISSUE TITLE
Error on line 32:  (Not all features seem to have been set on IfcSurfaceStyleRendering 9 / 10)

### ISSUE THREAD

**Issue by stestaub** [opensourceBIM/BIMserver#812]
With the latest BimServer release 101, we experienced an issue With IfcSurfaceStyleRendering of an IFC4 model. When uploading the model the server returned the following exception:

```
error on line 32:  (Not all features seem to have been set on IfcSurfaceStyleRendering 9 / 10) #50= IFCSURFACESTYLERENDERING(#48,*,$,$,$,$,$,$,.NOTDEFINED.);
```
I checked the documentation for IFC4 and this line seems to be correct. I also checked the file with Solibri Model Viewer and it loaded correctly.

Could this be an error in the implementation of BimViewer?

If you need the model to test it, I can send it to you by email.

Thanks for your help

**Comment by stestaub** [comment]
I found the problem about the checkin. It is the transparency attribute. If I set them to a value between 0 and one, the checkin works, although a lot of geometries are missing when viewing the model.

As the IFC4 specification describes, the transparency attribute is optional, so `IFCSURFACESTYLERENDERING(#48,*,$,$,$,$,$,$,.NOTDEFINED.);` should be correct but is not accepted by BimServer

**Comment by hlg** [comment]
Are you sure about the star? AFAIK, the star is is meant for explicit attributes which are overridden as derived attributes. Then the unset value is called _omitted_ value. If an optional attribute's value is unset, it is called _indefinite_ value and dollar must be used. I think the transparency attribute falls in the latter category.

I am not sure whether derived attributes overriding explicit attributes exist in IFC at all. If not, it might be fine to just ignore the stars while parsing since they should not appear anyway.

**Comment by stestaub** [comment]
Thanks for the input. No I was actually not sure about the star. I tried by changing the star to $ and I could successfully check in.

So it seems the software does not export valid IFC4. Anyway, I agree with @hlg that it might be a good idea to ignore stars.

**Comment by rubendel** [comment]
The exporting software is definitely at fault here. I am not in favor of changing this behaviour in BIMserver as we try to stay as close to the standard as we can.
