### ISSUE TITLE
change name of user

### ISSUE THREAD

**Issue by oliviersaintgobain** [opensourceBIM/BIMserver#832]
Hello,
I would like to know how to change the name of a user...after a mistake.
it's not possible de remove it so, how to change his name ?
thanks.

Olivier

**Comment by rubendel** [comment]
That's not possible with the current API. Since BIMserver is mainly used as a BIM-specific database (using just one user account), we are not spending much time on improving the user-management features. It should be fairly trivial to add this functionality though, pull requests are always welcome.

I think it is possible to delete users btw.
