### ISSUE TITLE
Get Properties of Elements

### ISSUE THREAD

**Issue by mattmagoobim** [opensourceBIM/BIMserver#867]
Is it possible to get all Parameters about all the elements in the model using the JSON API?

I've been having a look and can only get to the IfcRelDefinesByProperties datasets, which then requre additional looping through queries.

I'd like to end up with something similar to how BimView displays the Properties of an element

Thanks for any help

**Comment by mattmagoobim** [comment]
I believe I understand a the tokenising of the BIMView APInow, 

So while I still have to dig into the structure I can query an array of Oids and which returns a topicid. which can then be queried to reduce the number of queries down dramatically.

I'm not sure if this is the most efficient way, so I'd be keen to understand if there's a better system

**Comment by rubendel** [comment]
Here is an example query that will get all IfcWall objects and their properties which are defined in PropertySets.

```json
{
  "doublebuffer": true,
  "type": {
    "name": "IfcWall",
    "includeAllSubTypes": true
  },
  "includes": [
    {
      "type": {
        "name": "IfcWall",
        "includeAllSubTypes": true
      },
      "fields": [
        "IsDefinedBy"
      ],
      "includes": [
        {
          "type": "IfcRelDefinesByProperties",
          "fields": [
            "RelatingPropertyDefinition"
          ],
          "includes": [
            {
              "type": "IfcPropertySet",
              "fields": [
                "HasProperties"
              ]
            }
          ]
        }
      ]
    },
    "validifc:ContainedInStructure",
    "validifc:OwnerHistory"
  ]
}
```

Double buffering: Because we like a consistent tree and objects can be referred from all over the place
validifc:ContainedInStructure: To get the actual tree, required to make it a valid IFC file
validifc:OwnerHistory: To make it a valid IFC file

The IFC geometry is omitted from this example, so you end up with a reasonable small IFC file.

If you are not serializing to IFC you can leave those last 2 out, possibly the double buffering too.

**Comment by rubendel** [comment]
This example has been added to the BIMvie.ws examples as well
