### ISSUE TITLE
Which version of BIMserver is recommended?

### ISSUE THREAD

**Issue by sellingsolutions** [opensourceBIM/BIMserver#882]
I'm running Tomcat8 on Ubuntu 16 and I've tried all of the versions listed below:

Since the bimserverapi doesn't work I can't upload ifc files? That's at least what it seems like when I try to 'check in' an ifc file.

So my goal right now is to be able to:
1. Use the BIMServerAPI to create a project
2. Use the BIMServerAPI to Upload an ifc file to said project
3. Use the BIMServerAPI to split the ifc file into small ifc files based on queries

**1.5.113**
```
Installing bimsurfer...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.bimsurfer

		Installing bimviews...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.bimviews

		Installing ifcopenshellplugin...
		Successfully installed IfcOpenShellPlugin (org.opensourcebim:ifcopenshellplugin:0.5.35)

		Installing ifcplugins...
		Successfully installed IfcPlugins (org.opensourcebim:ifcplugins:0.0.41)

		Installing binaryserializers...
		Successfully installed BinarySerializers (org.opensourcebim:binaryserializers:0.0.41)

		Installing bimserverapi...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.bimserverapi

		Installing console...
		Successfully installed Console (org.opensourcebim:console:0.0.16)

		Installing gltf...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.gltf

		Installing mergers...
		Successfully installed Mergers (org.opensourcebim:mergers:0.0.17)
```
**1.5.111**
Same result as 1.5.113

**1.5.109**
```
org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found
```

**1.5.108**
```
org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found
```

**1.5.101**
```
Installing ifcplugins...
		org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found
		Setup aborted
```

**1.5.95**
```
Installing ifcplugins...
		org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found
		Setup aborted
```
**1.5.92**
```
	Installing plugins...
		Installing bimsurfer...
		Successfully installed BIMsurfer (org.opensourcebim:bimsurfer:0.0.47)

		Installing bimviews...
		Successfully installed BIMvie.ws (org.opensourcebim:bimviews:0.0.112)

		Installing ifcopenshellplugin...
		Successfully installed IfcOpenShellPlugin (org.opensourcebim:ifcopenshellplugin:0.5.36)

		Installing ifcplugins...
		org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found
		Setup aborted
```
**1.5.81**
```
Installing ifcplugins...
		org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found
		Setup aborted
```
none of them are able to install **all** of the default plugins in the bimserver installation wizard

**Comment by taliu** [comment]
use version  1.5.111
I have the same problem...

**Comment by rubendel** [comment]
I'm sorry it's a mess currently, I am planning to make new builds next Friday.

**Comment by rubendel** [comment]
1.5.117 has been tested, both JAR and WAR, all default plugins are available.

**Comment by cacu100** [comment]
I'm testing the version 1.5.117 But I can install the collada serializer plugin. I was using the version 1.5.101 and it was working well, but I lost my configuration because I had a problem on server. Now the same version doesn't work well and the newest version is wrong.

**Comment by auvinenak** [comment]
I Installed 1.5.117 8th of january and everything worked.
Today I tried to do it again and:

Installing bimsurfer...
No plugin bundle available for your version of BIMserver: org.opensourcebim.bimsurfer

Installing bimviews...
No plugin bundle available for your version of BIMserver: org.opensourcebim.bimviews

**Comment by rubendel** [comment]
The following seems to be happening: BIMserver only checks the latest 3 versions of a any given plugin, if none of these match the BIMserver version, you get the aforementioned error message. This is obviously a bug in BIMserver, it should keep trying older versions until it finds one that matches.

In this case both bimsurfer and bimviews have > 3 releases newer than 1.5.117.

This bug can't be fixed in an older version, but we can try to keep the amount of plugin updates < 3 for now. A new release will be online shortly.

**Comment by Jimmy-Abualdenien** [comment]
Thanks @rubendel I'm able to use the latest now. However, the gtlf plugin is the only plugin that's not being installed with the same problem (no version available).

Tested creating a project and checking in an IFC file, it works as expected and I'm able to see the 3D model as well (expected not to be able to see it since gtlf was not installed).

**Comment by Jimmy-Abualdenien** [comment]
Thanks @rubendel it installs now successfully. However, I've noticed a minor issue with the bimserverclient installation (probably require creating a different issue). Its JS files are installed outside the bimserver directory, i.e directly on the localhost. In case the server is installed in a subdirectory, then it won't be able to locate the js file, which will cause the bimviews not to run.

http://localhost:8080/apps/bimserverjavascriptapi/bimserverclient.js
Instead of 
http://localhost:8080/{bimserverDir}/apps/bimserverjavascriptapi/bimserverclient.js

Thanks.

**Comment by rubendel** [comment]
Hmm yes this is not tested much, I always run on a root context, seems nicer anyways (this way the URL also does not change when installing another version of BIMserver)

**Comment by Jimmy-Abualdenien** [comment]
I agree with you it looks better to use the root. 
To correct my previous comment, the api is installed inside the bimserver directory, but the bimviews is trying to fetch them from the root directory which causes the bimviews not to run (it throws 404 exceptions for the client api js files).

**Comment by hlg** [comment]
I am running BIMserver in Tomcat, too. I also use a subdirectory, because I want to run another application in the same application server. I still keep the BIMserver URL stable across version updates. In my experience, BIMvie.ws runs just fine with this setup, you just have to make sure that the site address includes the BIMserver directory. It seems as if your's is set to root, i.e. `http://localhost:8080` instead of `http://localhost:8080/{bimserverDir}`.

If you missed to set it right during setup or accidentally messed it up and can not change it through BIMvie.ws now, you still have the option to correct it through the API, e.g. via REST. Since you are on Linux, you can just try curl: First sign in and get a token, then use that token to change the address:

    curl --data  '{"request": {"interface": "AuthInterface", "method": "login", "parameters": {"username": "<user>", "password": "<pw>"}}}' http://localhost:8080/<bimserverDir>/json
    curl --data  '{"token": "<token>", "request" : {"interface": "SettingsInterface", "method": "setSiteAddress", "parameters": {"siteAddress": "http://localhost:8080/<bimserverDir>"}}}' http://localhost:8080/<bimserverDir>/json

You can also check the site address before and after setting it:

    curl --data  '{"token": "<token>", "request": {"interface": "SettingsInterface", "method": "getSiteAddress", "parameters": {}}}' http://localhost:8080/<bimserverDir>/json

**Comment by rubendel** [comment]
@hlg @Jimmy-Abualdenien Yes both correct.

What I did just now is make the imports relative, that should work on a non-root context path as well. 

BIMvie.ws was originally also meant to be able to run loaded from a regular webserver, that's obviously broken now unless you reconstruct the original paths (e.a. put the bimserver js api in the right relative place).

https://github.com/opensourceBIM/bimvie.ws

**Comment by hlg** [comment]
I have just tested with the [1.5.123 release](https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.123) and it seems to work fine again.
