### ISSUE TITLE
1.5.117 Geometry Not Being Created

### ISSUE THREAD

**Issue by pidnee** [opensourceBIM/BIMserver#890]
Many of the IFC's I am loading into 1.5.117 are not generating geometry. They look like they have worked, the tree is viewable. However on many models there is no 3D preview. When I download the file and convert to obj I get a no geometry to convert error also.
These IFCs worked ok in the 1.5.9x BIMserver install I had.

**Comment by snlu1902** [comment]
I have the same issue, any solution?

**Comment by pidnee** [comment]
> Any error messages?

No error messages in the logs I could see. Everything seemed happy, on some IFC's I even got what looked like a tree in BIMvie.ws.

**Comment by hlg** [comment]
We see some of the new IFC4 geometry types (those with two-dimensional arrays) not being generated, apparently because the partial IFC passed to IfcOpenShell is incomplete. For example, for instances of `IfcPolygonalFaceSet`, using the [example file from IFC4 specification](http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/annex/annex-e/polygonal-face-tessellation.ifc), these lines

    #15= IFCCARTESIANPOINTLIST3D(((-10000.0,-10000.0,-10000.0),(10000.0,-10000.0,-10000.0), ...);
    #16= IFCINDEXEDPOLYGONALFACE((2,6,5,1));
    ...
    #27= IFCPOLYGONALFACESET(#15,.T.,(#16,#17,#18,#19,#20,#21,#22,#23,#24,#25,#26),$);

are reaching IfcOpenShell (according to the debug file) as

    #26= IFCPOLYGONALFACESET($,.T.,(),$);

From the `IfcPolygonalFaceset`, both the first parameter (Coordinates, IfcCartesianPointList3D) and third parameter (Faces, list of IfcIndexedPolygonalFace) are missing.

@pidnee, can you check the geometry generation report in BIMvie.ws / project / tab "Extended data" whether you see similar errors?

**Comment by hlg** [comment]
I found different reasons why geometry might not be generated:

1. it is not included in the ifc4stdlib representation query (see #903)
2. it is not supported by IfcOpenShell (see https://github.com/IfcOpenShell/IfcOpenShell/issues/503)

These issues may appear isolated or in combination.

**Comment by hlg** [comment]
This was likely due to IFC4 geometry missing and resolved in the meantime.
