### ISSUE TITLE
Documentation about plans and goals

### ISSUE THREAD

**Issue by mihajlom** [opensourceBIM/BIMserver#892]
Hi there

I can't find any document related to some of the plans and goals for this project. Can you point me at some directions?

Some important changes happened and I had to rework some parts of the project I work on. Some information about the plans would allow me (and probably some others) to make proper decisions on planning and designing systems that are using opensourceBIM server with plugins.

I think everyone can benefit if I share use-case on my project (actually the project that I inherited).

It is a document management application with module to display 3D view of the models of the projects stored on BIMserver done in Angular with three.js library. Client needs to support for IFC4 (that was not part of the project) so we decided that it is a good time for update whole stack.

Model was downloaded with BinaryGeometryMessagingStreamingSerializer2
that is now removed from BinarySerializers plugin (yes, I understand that original BinaryGeometryMessagingStreamingSerializer didn't support queries and now it does, so cleanup could be done) but that introduced also changes in binary format so I had to adopt the code to be able to read the data correctly.

The day when I was done with the update, I saw the commit that was adding buffers... 
https://github.com/opensourceBIM/BinarySerializers/commit/8da1bd635f43c0f156adee0c4c0029ece62dabc0

And I haven't check the things after, but as version changed, that probably means that my code will not work anymore.

Sorry if some of my understanding is wrong, but I still fresh with BIMserver and it's implementations.

**Comment by rubendel** [comment]
Great that you are using BIMserver! Unfortunately the project is not yet in the stage where we can publish year-long roadmaps, if we would they would probably never be met. Most of the work is basically research and trying to solve problems that arise.

For example the added buffers you talk about were added to allow viewers to directly send those buffers to the GPU. This was the result of measured slowliness of viewers, not really something we can plan ahead.

Upgrading to a newer version is always a tradeoff. I hope you would only upgrade because of certain added features or fixed bugs, the tradeoff being having to rework some of your own code. That is probably the same in all opensource projects.

From your point of view I can completely understand the need for such documentation, and I really hope the project will get to the point where we can plan ahead more than a few weeks. For us to get there faster a very big help would be actual contributions to the code (which we haven't got a lot).
