### ISSUE TITLE
Problem with 3D

### ISSUE THREAD

**Issue by LMonir** [opensourceBIM/BIMserver#926]
Hi, 

I got an StreamingGeometryGenerator after loading a model an clicking on the eye.
_ERROR [pool-1-thread-1] o.b.g.StreamingGeometryGenerator [StreamingGeometryGenerator.java:590] Number of erroneous files: 14_

Under 3D I can't see anything but the model is loaded.

**Comment by rubendel** [comment]
A lot of information is missing here, for example the version numbers of BIMserver and plugins. Also the error message cannot possibly popup after "clicking the eye" since the error message is generated during checkin.

You can view the "Geometry generation report" linked to the revision as extended data to get more information about which geometries were not successfully generated. If you post it here (preferably with the IFC file) we can check what the problem is.

**Comment by LMonir** [comment]
Sorry for the missing information. I found out that some user permissions missing on my PC caused the problem. Unfortunately, I do not know which one, but it works on my own PC.
