### ISSUE TITLE
Version 117 does not produce geometry after installing version 125 in parallel

### ISSUE THREAD

**Issue by epeter-** [opensourceBIM/BIMserver#943]
System: Windows 10 64 bit
Starting BIM Server from batch file and BIMserver Starter and launching a webbrowser

history: BIMserver was running as expected till yesterday, when i tried to install a version 125 in parallel.
all plugins were reinstalled manually  as for the 117 version.

**Describe the bug**
I upload a IFC file 2x3 - a simple test file
Upload is correct, i can examine the tree, so everything looks fine
![image](https://user-images.githubusercontent.com/6928491/53163150-c3bcaa00-35cd-11e9-8c83-9bcf46fbbbb3.png)

when i click on the "eye" icon to visualize the model sometimes for some models an error message is shown:

![image](https://user-images.githubusercontent.com/6928491/53163011-7b04f100-35cd-11e9-8959-d4e52e1b8165.png)

sometimes simply no 3d is not shown.

**To Reproduce**

checkin new ifc to project, try to visualize 3d

**Expected behavior**
show 3d

**Comment by JonasManuelKonstruktum** [comment]
We are having the same problem after only restarting 117.

**Comment by JonasManuelKonstruktum** [comment]
The issue seems to be that the server returns broken json like this:
```
{
		"_i": 17486907238,
		"_t": "GeometryInfo",
		"_s": 1,
		"_ebounds": {
			"_t": "Bounds",
			"min": {
				"_t": "Vector3f",
				"x": NaN,
				"y": NaN,
				"z": NaN
			},
			"max": {
				"_t": "Vector3f",
				"x": NaN,
				"y": NaN,
				"z": NaN
			}
		},
		"_eboundsUntransformed": {
			"_t": "Bounds",
			"min": {
				"_t": "Vector3f",
				"x": NaN,
				"y": NaN,
				"z": -1.51996493463552E14
			},
			"max": {
				"_t": "Vector3f",
				"x": NaN,
				"y": NaN,
				"z": 2.1733438968658447
			}
		},
		"primitiveCount": 788,
		"transformation": "AAAAAAAAAAAAAAAAAADwvwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAKEAAAAAAAAAkQJqZmZmZmQVAAAAAAAAA8D8=",
		"area": 0.0,
		"volume": 0.0,
		"hasTransparency": false,
		"ifcProductOid": 98109167,
		"density": NaN,
....
```
that contains  a lot of NaN values.
Maybe this is not a geometry generation issue but encoding issue when sending to the client.
However I am  completely lost as to what changed, because we only restarted our server for maintainance without changing the configuration.

**Comment by rubendel** [comment]
Unfortunately there were a few versions of the IfcOpenShell plugin that - independently from the BIMserver plugin system - downloaded potential new versions of the binaries. We thought that would be useful for development purposes, but it turned out not to be. This has now changed, you as the user can now explicitly tell it to load a different version.

This only happened when restarting a BIMserver, which would explain why it happened at that point. The reason for the NaN is that the geometry would not be calculated correctly, and therefore also a lot of other properties were not.

BIMserver 1.5.125 and the IfcOpenShell plugin linked to it does not have this behaviour.

**Comment by klacol** [comment]
We have encountered the same issue with BIMserver 1.5.117 as @epeter-  and @JonasManuelKonstruktum.  Thanks for reporting it so in detail.

It came suddenly, but we cannot asure, that the server was NOT restarted in between by somebody from our organization. So the restart could have been the explanation.

Is the only fix, an update to version 1.5.125, or is there another workaround?

**Comment by epeter-** [comment]
Er found out that version 125 has problems reporting properties, but  are still exploring / testing

**Comment by klacol** [comment]
We found out, dass this issue is probably related to this issue:
https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/issues/9

The conclusion in our internal ticket system is:

> So we have to bite the bullet.
The models uploaded before the BIMserver restart can still be displayed. However, uploading new revisions will prevent the models from being displayed.
I had *** committed to '***.ARC' before restarting.
Display worked. Now after the restart the 2nd revision committed.
SyntaxError: Unexpected token N in JSON at position...

> BIMserver update to 1.5.125 is then probably pending.
 Update our project to current BIMserver API
 change/test all method calls
 change/test all string queries to the BIMserver
 validifc has been renamed to ifc2x3tc1-stdlib
 test concerns mapping and BIMexplorer
 Create a new BIMserver setup

Is this the best way forward?

**Comment by JonasManuelKonstruktum** [comment]
would it be possible to re-release a version of the IfcOpenShell plugin that disables this behaviour and ist compatible to 117?

**Comment by hlg** [comment]
As a workaround I was successful to replace the binary manually. However you have to rename it to reflect the commit-sha of the release that BIMserver tries to download. This is quite dirty and opens the door to all sorts of confusion, since it obfuscates which IfcOpenShell version you are actually using.

**Comment by klacol** [comment]
> As a workaround I was successful to replace the binary manually. However you have to rename it to reflect the commit-sha of the release that BIMserver tries to download. This is quite dirty and opens the door to all sorts of confusion, since it obfuscates which IfcOpenShell version you are actually using.

And we would have to find a way to stop the automatic download of a new version on every restart.

**Comment by epeter-** [comment]
and, in terms of versioning it might be a good idea to really create "versions" and not something between. it shall not be that a new release affects any installed ancestors!

**Comment by klacol** [comment]
@epeter- Could you explain us the steps, that are needed to reset the plugins for an existing installation? Thanks!

**Comment by hlg** [comment]
> And we would have to find a way to stop the automatic download of a new version on every restart.

If a file with the same name is already there it will not be overwritten (at least on Windows, did not test other OS). You may want to stop the server anyway for replacing the file and restart after.

> and, in terms of versioning it might be a good idea to really create "versions" and not something between. it shall not be that a new release affects any installed predecessors!

I think it is well-understood what is wrong with these plugin versions. I just shared a quick-and-dirty workaround for those (like me) who insist on using outdated plugin versions such as 0.5.38 which works with BIMserver 1.5.117. This should work both for a new setup of the old BIMserver version as well as for existing installations.

**Comment by epeter-** [comment]
@klacol - unfortunately not as @hlg solved that and i am still failing.
@

**Comment by klacol** [comment]
Hey @epeter- , this worked for us:

1. Stop BIMserver
2. Goto folder "..\Database\tmp\org.opensourcebim.ifcopenshellplugin"
3. Delete "IfcGeomServer-v0.6.0-33cbcc2-win64.exe"
4. Rename "IfcGeomServer-v0.6.0-4380e1d-win64.exe" to "IfcGeomServer-v0.6.0-33cbcc2-win64.exe"
5. Start BIMserver again

Then a commit and a visualization worked again.

**Comment by rubendel** [comment]
@klacol Yes that sounds like the perfect workaround.

We will not release a new version of the IOS plugin, simply to fix a (_development_) version of BIMserver.

@epeter- You are correct, as explained, this is now fixed in newer versions.

**Comment by cacu100** [comment]
Hey @epeter- and klacol.
I have the same issue. I have a 1.5.117 war installation over tomcat in Centos OS. I can't find  "..\Database\tmp\org.opensourcebim.ifcopenshellplugin" How can I fix it.
Thanks

**Comment by hlg** [comment]
@cacu100 it is just `tmp\org.opensourcebim.ifcopenshellplugin`in the home folder of your BIMserver install. In @klacol's case the home folder this seems to be called `Database`, for you it is probably different.

**Comment by cacu100** [comment]
Thanks @hlg very useful the information provided. I found the folder inside my webapps folder. Now I need know how can I get IfcGeomServer-v0.6.0-4380e1d executable file for linux to replace it inside this folder. In https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/issues/9 @stegh provide the link to download the file for windows. But I'm using Centos

**Comment by hlg** [comment]
Replace `win32` with `linux32`or `linux64`.

**Comment by cacu100** [comment]
Thanks @hlg. Nice

**Comment by klacol** [comment]
> In @klacol's case the home folder seems to be called `Database`, for you it is probably different.

Ah, yes, we are running on Tomcat, and there the folder is configured in the server.xml and there in the param "homedir" of the host. So, this folder will be in different locations based on the environment.

**Comment by cacu100** [comment]
Thanks @klacol for your reply. Yes, I found the correct path and file to replace on this version.

**Comment by rubendel** [comment]
I think the original issue is resolved, closing.
