### ISSUE TITLE
Using filters in Cesium

### ISSUE THREAD

**Issue by rickklooster** [opensourceBIM/BIMserver#983]
We are experimenting with using the Cesium connection to display BIM models in Cesium. It already kind of works (check https://3drotterdam.nl/ruggedised/#/ & turn on 'Zwembad' & 'Kunstenpand'), but since these are the full models it's quite heavy. 

<img width="1919" alt="Schermafbeelding 2019-05-22 om 22 19 48" src="https://user-images.githubusercontent.com/15192316/58230130-c0070380-7d33-11e9-8446-b5184e097cb5.png">

Is there more information on how the filters work on the cesium to select just certain content from the BIM server? Hope this way we can scale it down a little ;)

**Comment by rubendel** [comment]
There are a few ways to query less geometry, all of them are based on leaving out certain objects. BIMserver has no notion of LOD at the moment.

As a base line, this will get you all objects:
```json
{
  "type": {
    "name": "IfcProduct",
    "includeAllSubTypes": true
  }
}
```

To only get certain types (IfcWall has includeAllSubTypes enabled because it has a few subtypes like IfcWallStandardCase):
```json
{
  "types": [{
    "name": "IfcWall",
    "includeAllSubTypes": true
  }, {
    "name": "IfcSlab"
  }, {
    "name": "IfcRoof"
  }]
}
```

Obviously, selecting on the types is not always a good fit. Some authoring tools export all objects in a model as the same type (usually IfcProxy or IfcBuildingElementProxy).

The following query will only give you objects with a given "density" [0]. Basically what you do here is you query for the root tile (BIMserver uses tiles as well) of a virtual octree with depth=0 (a complicated way of saying, the whole model). In this case all objects with a density between 0 and 10 are returned. You can tweak the numbers of course.
```json
{
  "type": {
    "name": "IfcProduct",
    "includeAllSubTypes": true
  },
  "tiles": {
    "ids": [0],
    "densityLowerThreshold": 10,
    "densityUpperThreshold": 0,
    "maxDepth": 0
  }
}
```

[0] In BIMserver, density is currently defined as: "The amount of triangles an object has, divided by the area (in m2) of the largest face of the axis aligned bounding box of the object". The rationale behind this is actually a good fit for your use case, since it's a tradeoff between size (in bytes) and as how many pixels objects are potentially going to show up in a viewer.

**Comment by sergeiknysh** [comment]
@rickklooster let me know please did you succeed whith this approach from @rubendel ?
I try to solve the same problem.
